"""Generate the shared Python/CUDA Direct INT4 layout constants."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "python/sglang/srt/mem_cache/kvbit_dsv4_format.json"
PYTHON_OUTPUT = ROOT / "python/sglang/srt/mem_cache/kvbit_dsv4_layout_constants.py"
CPP_OUTPUT = ROOT / "python/sglang/kernels/aot/csrc/kvbit/flashmla/packed_layout.h"


def render(schema: dict) -> dict[Path, str]:
    # This generator describes one codec, not an arbitrary quantization DSL.
    expected = {
        "format_id": "dsv4_int4_sym_g32_e4m3",
        "version": 1,
        "nope_dim": 448,
        "rope_dim": 64,
        "group_size": 32,
        "bits": 4,
        "scale_dtype": "e4m3fn",
        "scale_rounding": "nearest_even",
        "code_range": [-7, 7],
        "rope_dtype": "bfloat16",
        "transform": "none",
        "header_alignment": 16,
        "native_row_bytes": 584,
        "layouts": {
            "aos_368": {"row_alignment": 16},
            "aos_384": {"row_alignment": 128},
        },
    }
    if schema != expected:
        raise ValueError(
            "Unsupported codec schema; update the codec and ABI version first"
        )

    def align(value: int, alignment: int) -> int:
        return (value + alignment - 1) // alignment * alignment

    num_groups = schema["nope_dim"] // schema["group_size"]
    code_bytes = schema["nope_dim"] * schema["bits"] // 8
    header_bytes = align(num_groups, schema["header_alignment"])
    rope_offset = code_bytes + header_bytes
    rope_bytes = schema["rope_dim"] * 2
    payload_bytes = rope_offset + rope_bytes
    constants = {
        "FORMAT_VERSION": schema["version"],
        "NOPE_DIM": schema["nope_dim"],
        "ROPE_DIM": schema["rope_dim"],
        "GROUP_SIZE": schema["group_size"],
        "BITS": schema["bits"],
        "NUM_GROUPS": num_groups,
        "CODE_BYTES": code_bytes,
        "HEADER_OFFSET": code_bytes,
        "HEADER_BYTES": header_bytes,
        "ROPE_OFFSET": rope_offset,
        "ROPE_BYTES": rope_bytes,
        "PAYLOAD_BYTES": payload_bytes,
        "COMPACT_ROW_BYTES": align(payload_bytes, 16),
        "ALIGNED_ROW_BYTES": align(payload_bytes, 128),
        "NATIVE_ROW_BYTES": schema["native_row_bytes"],
    }
    fingerprint = hashlib.sha256(
        json.dumps(schema, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    banner = "Generated by scripts/kvbit/generate_dsv4_layout.py; do not edit."
    python = (
        f'"""{banner}"""\n\n'
        f'FORMAT_ID = "{schema["format_id"]}"\n'
        f'SCHEMA_SHA256 = "{fingerprint}"\n'
        + "".join(f"{name} = {value}\n" for name, value in constants.items())
    )
    cpp = (
        f"// {banner}\n"
        "#pragma once\n\n"
        "namespace kvbit::dsv4 {\n"
        f'inline constexpr char FORMAT_ID[] = "{schema["format_id"]}";\n'
        f'inline constexpr char SCHEMA_SHA256[] = "{fingerprint}";\n'
        + "".join(
            f"inline constexpr int {name} = {value};\n"
            for name, value in constants.items()
        )
        + "static_assert(ROPE_OFFSET % 16 == 0);\n"
        "static_assert(PAYLOAD_BYTES <= COMPACT_ROW_BYTES);\n"
        "static_assert(ALIGNED_ROW_BYTES % 128 == 0);\n"
        "}  // namespace kvbit::dsv4\n"
    )
    return {PYTHON_OUTPUT: python, CPP_OUTPUT: cpp}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render(json.loads(SCHEMA.read_text()))
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        print("Stale Direct INT4 ABI files:\n" + "\n".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
