{
 "title": "SGLang Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "model_name", "label": "name", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Max Running Requests",
   "type": "stat",
   "description": "max-running-requests from server argument",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sglang:max_running_requests{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Context Length",
   "type": "stat",
   "description": "Supported context length with loaded model",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sglang:context_len{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Total Num Tokens",
   "type": "stat",
   "description": "max_total_tokens",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sglang:max_total_num_tokens{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Prefill Tokens",
   "type": "stat",
   "description": "max_prefill_tokens from server args",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sglang:max_prefill_tokens{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Tokens",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sglang:cached_token{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sglang:cache_hit_rate{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "E2E Request Latency (S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(sglang:e2e_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(sglang:e2e_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(sglang:e2e_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(sglang:e2e_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(sglang:e2e_request_latency_seconds_sum{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval]) / rate(sglang:e2e_request_latency_seconds_count[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Generation Throughput (Token / S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    { "expr": "sglang:gen_throughput", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Num Requests Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sglang:num_requests_running{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sglang:num_requests_waiting{instance=\"$instance\", name=\"$model_name\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Time Request Decoding (S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(sglang:decode_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(sglang:decode_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(sglang:decode_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(sglang:decode_request_latency_seconds_bucket{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(sglang:decode_request_latency_seconds_sum{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval]) / rate(sglang:decode_request_latency_seconds_count[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Time Request Waiting (S)",
   "type": "timeseries",
   "description": "Time requests waiting before added to batch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(sglang:waiting_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(sglang:waiting_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(sglang:waiting_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(sglang:waiting_request_latency_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(sglang:waiting_request_latency_seconds_sum[$__rate_interval])\r\n/\r\nrate(sglang:waiting_request_latency_seconds_count[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(sglang:request_prompt_tokens_sum{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])) by (instance, name)",
     "legendFormat": "{{__name__}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Generated Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(sglang:request_generation_tokens_sum{instance=\"$instance\", name=\"$model_name\"}[$__rate_interval])) by (instance, name)",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Request Prompt Tokens (WIP)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(le) (increase(sglang:request_prompt_tokens_bucket{name=\"$model_name\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Request Generation Tokens (WIP)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(le) (increase(sglang:request_generation_tokens_bucket{name=\"$model_name\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}