"""Background disk cleaner for the NIXL FILE HiCache backend."""

from __future__ import annotations

import concurrent.futures
import logging
import os
import re
import threading
import time
from dataclasses import dataclass, field
from typing import Callable, Iterable, Optional

from sglang.srt.mem_cache.hicache_storage import PoolName
from sglang.srt.mem_cache.storage.nixl.nixl_routing import BUCKET_HEX_CHARS

logger = logging.getLogger(__name__)

_DEFAULT_INTERVAL_SEC = 30.0
_DEFAULT_RECHECK_GROUPS = 50
_DEFAULT_HIGH_WATERMARK = 80.0
_DEFAULT_LOW_WATERMARK = 70.0
# In filesystem-usage mode, warn once when the storage dirs hold less than this
# fraction of the used bytes on their filesystem (likely a shared volume).
_SHARED_VOLUME_WARN_FRACTION = 0.1
_RANK_SUFFIX_RE = re.compile(r"_(\d+)_(\d+)$")
_KV_SUFFIXES = ("_k", "_v")
_POOL_NAME_PATTERN = "|".join(
    sorted((re.escape(pool.value) for pool in PoolName), key=len, reverse=True)
)
_HYBRID_COMPONENT_SUFFIX_RE = re.compile(
    rf"_(?:{_POOL_NAME_PATTERN})(?:_(?:temporal|conv_\d+|[kv]|\d+))?$"
)
_BUCKET_NAME_RE = re.compile(rf"^[0-9a-f]{{{BUCKET_HEX_CHARS}}}$")


@dataclass
class _GroupInfo:
    """Metadata for one logical cache key group in a cleaner tick."""

    base_key: str
    mtime: float = 0.0
    size: int = 0
    paths: set[str] = field(default_factory=set)
    # Physical files in one logical group can hash to different base dirs
    # because TP-rank and zero-copy K/V suffixes are part of the routed key.
    base_dirs: set[str] = field(default_factory=set)


def _parse_group_key(name: str) -> str:
    """Return the logical cache-key group for one NIXL FILE object name.

    The physical names are produced by ``HiCacheNixl._get_suffixed_key``,
    ``HiCacheNixl._get_key_list_from_meta``, and
    ``HiCacheNixl._get_hybrid_component_keys``.
    """
    stem = name
    stem = _HYBRID_COMPONENT_SUFFIX_RE.sub("", stem)
    for suffix in _KV_SUFFIXES:
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break

    match = _RANK_SUFFIX_RE.search(stem)
    if match is not None:
        stem = stem[: match.start()]
    return stem


def _safe_unlink(path: str) -> tuple[bool, int]:
    """Best-effort unlink; returns whether a file was removed and its size."""
    try:
        size = os.stat(path).st_size
        os.unlink(path)
        return True, size
    except FileNotFoundError:
        logger.debug("NIXL L3 file already removed before cleanup: %s", path)
        return False, 0
    except OSError:
        logger.debug("Failed to unlink NIXL L3 file %s", path, exc_info=True)
        return False, 0


class HiCacheL3Cleaner:
    """Delete old NIXL FILE cache entries when disk usage exceeds watermarks.

    By default, usage is the fill level of the filesystem containing each
    storage directory (``os.statvfs``). When ``capacity_gb`` is set, usage is
    instead the total size of the NIXL FILE objects under all storage
    directories relative to that budget, so data outside the cache on a shared
    volume does not trigger cleanup.

    Cleanup operates on physical file names only, so it is compatible with MHA,
    MLA, and DSA naming as long as the keys are generated by ``HiCacheNixl``.
    """

    def __init__(
        self,
        storage_dirs: list[str] | str,
        tp_rank: int,
        *,
        high_watermark: float = _DEFAULT_HIGH_WATERMARK,
        low_watermark: float = _DEFAULT_LOW_WATERMARK,
        interval_sec: float = _DEFAULT_INTERVAL_SEC,
        recheck_groups: int = _DEFAULT_RECHECK_GROUPS,
        unlink_workers: Optional[int] = None,
        capacity_gb: Optional[float] = None,
    ) -> None:
        if isinstance(storage_dirs, str):
            storage_dirs = [storage_dirs] if storage_dirs else []
        self.storage_dirs = [path for path in storage_dirs if path]
        self.tp_rank = tp_rank
        self.high_watermark = high_watermark
        self.low_watermark = low_watermark
        self.interval_sec = interval_sec
        self.recheck_groups = max(1, recheck_groups)
        self.capacity_bytes = (
            int(capacity_gb * (1024**3)) if capacity_gb is not None else None
        )
        self.unlink_workers = unlink_workers or max(
            8, 8 * max(len(self.storage_dirs), 1)
        )

        if self.low_watermark >= self.high_watermark:
            raise ValueError(
                "L3 cleaner low_watermark must be lower than high_watermark "
                f"(low_watermark={self.low_watermark}, "
                f"high_watermark={self.high_watermark})"
            )
        if self.capacity_bytes is not None and self.capacity_bytes <= 0:
            raise ValueError(
                f"L3 cleaner capacity_gb must be positive (capacity_gb={capacity_gb})"
            )

        self._stop = threading.Event()
        self._thread: Optional[threading.Thread] = None
        self._shared_volume_warned = False

    def start(self) -> None:
        """Start the cleaner thread on TP rank 0."""
        if self.tp_rank != 0 or not self.storage_dirs:
            return
        if self._thread is not None and self._thread.is_alive():
            return
        self._thread = threading.Thread(
            target=self._loop, name="hicache-l3-cleaner", daemon=True
        )
        self._thread.start()
        logger.info(
            "HiCacheL3Cleaner started: dirs=%s high=%.1f%% low=%.1f%% "
            "interval=%.1fs unlink_workers=%d usage=%s",
            self.storage_dirs,
            self.high_watermark,
            self.low_watermark,
            self.interval_sec,
            self.unlink_workers,
            (
                f"capacity {self.capacity_bytes / (1024**3):.2f} GiB"
                if self.capacity_bytes is not None
                else "filesystem"
            ),
        )

    def stop(self) -> None:
        """Stop the cleaner thread if it was started."""
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=5.0)
            self._thread = None

    def _disk_usage_bytes(self, path: str) -> Optional[tuple[int, int]]:
        """Return ``(used, total)`` bytes of the filesystem containing path."""
        try:
            stat = os.statvfs(path)
        except OSError:
            return None
        total = stat.f_blocks * stat.f_frsize
        available = stat.f_bavail * stat.f_frsize
        return total - available, total

    def _disk_usage_pct(self, path: str) -> float:
        usage = self._disk_usage_bytes(path)
        if usage is None or usage[1] == 0:
            return 0.0
        return 100.0 * usage[0] / usage[1]

    def _capacity_pct(self, used_bytes: int) -> float:
        return 100.0 * used_bytes / self.capacity_bytes

    def _group_dirs_by_device(self, paths: Iterable[str]) -> dict[int, list[str]]:
        by_device: dict[int, list[str]] = {}
        for path in paths:
            try:
                device = os.stat(path).st_dev
            except OSError:
                continue
            by_device.setdefault(device, []).append(path)
        return by_device

    def _loop(self) -> None:
        while not self._stop.is_set():
            try:
                self._tick()
            except Exception:
                logger.warning("NIXL L3 cleaner tick failed", exc_info=True)
            if self._stop.wait(self.interval_sec):
                break

    def _tick(self) -> bool:
        if self.capacity_bytes is not None:
            return self._tick_capacity()

        initial_pcts = {path: self._disk_usage_pct(path) for path in self.storage_dirs}
        hot_dirs = {
            path for path, pct in initial_pcts.items() if pct >= self.high_watermark
        }
        if not hot_dirs:
            return False

        scan_start = time.perf_counter()
        groups: dict[str, _GroupInfo] = {}
        dir_bytes = {
            base_dir: self._scan_base_dir(base_dir, groups)
            for base_dir in self.storage_dirs
        }
        self._maybe_warn_shared_volume(hot_dirs, dir_bytes)

        ordered = sorted(
            (group for group in groups.values() if group.base_dirs & hot_dirs),
            key=lambda group: group.mtime,
        )
        if not ordered:
            return False

        deleted_groups, deleted_files, bytes_deleted = self._delete_oldest(
            ordered,
            lambda _bytes_deleted: all(
                self._disk_usage_pct(path) < self.low_watermark for path in hot_dirs
            ),
        )

        final_pcts = {path: self._disk_usage_pct(path) for path in self.storage_dirs}
        logger.info(
            "NIXL L3 cleanup: deleted %d groups / %d files (%.2f GiB) in %.1fs, "
            "initial_hot=%s final=%s",
            deleted_groups,
            deleted_files,
            bytes_deleted / (1024**3),
            time.perf_counter() - scan_start,
            {path: f"{initial_pcts[path]:.1f}%" for path in hot_dirs},
            {path: f"{pct:.1f}%" for path, pct in final_pcts.items()},
        )
        return True

    def _tick_capacity(self) -> bool:
        """Cleanup tick that watermarks the cache's own bytes against capacity."""
        # The cache cannot hold more bytes than are used on its filesystems, so
        # skip the directory scan while that upper bound is below the watermark.
        fs_used_bytes: Optional[int] = 0
        for paths in self._group_dirs_by_device(self.storage_dirs).values():
            usage = self._disk_usage_bytes(paths[0])
            if usage is None:
                fs_used_bytes = None
                break
            fs_used_bytes += usage[0]
        if (
            fs_used_bytes is not None
            and self._capacity_pct(fs_used_bytes) < self.high_watermark
        ):
            return False

        scan_start = time.perf_counter()
        groups: dict[str, _GroupInfo] = {}
        own_bytes = sum(
            self._scan_base_dir(base_dir, groups) for base_dir in self.storage_dirs
        )
        initial_pct = self._capacity_pct(own_bytes)
        if initial_pct < self.high_watermark:
            return False

        ordered = sorted(groups.values(), key=lambda group: group.mtime)
        deleted_groups, deleted_files, bytes_deleted = self._delete_oldest(
            ordered,
            lambda bytes_deleted: (
                self._capacity_pct(own_bytes - bytes_deleted) < self.low_watermark
            ),
        )

        logger.info(
            "NIXL L3 cleanup: deleted %d groups / %d files (%.2f GiB) in %.1fs, "
            "capacity=%.2f GiB initial=%.1f%% final=%.1f%%",
            deleted_groups,
            deleted_files,
            bytes_deleted / (1024**3),
            time.perf_counter() - scan_start,
            self.capacity_bytes / (1024**3),
            initial_pct,
            self._capacity_pct(own_bytes - bytes_deleted),
        )
        return True

    def _delete_oldest(
        self, ordered: list[_GroupInfo], done: Callable[[int], bool]
    ) -> tuple[int, int, int]:
        """Delete groups in order, checking ``done(bytes_deleted)`` per batch."""
        deleted_groups = 0
        deleted_files = 0
        bytes_deleted = 0

        with concurrent.futures.ThreadPoolExecutor(
            max_workers=self.unlink_workers,
            thread_name_prefix="hicache-l3-unlink",
        ) as pool:
            idx = 0
            while idx < len(ordered) and not self._stop.is_set():
                batch = ordered[idx : idx + self.recheck_groups]
                paths = list(self._iter_group_paths(batch))
                for removed, removed_bytes in pool.map(_safe_unlink, paths):
                    if removed:
                        deleted_files += 1
                        bytes_deleted += removed_bytes
                deleted_groups += len(batch)
                idx += len(batch)

                if done(bytes_deleted):
                    break
        return deleted_groups, deleted_files, bytes_deleted

    def _maybe_warn_shared_volume(
        self, hot_dirs: set[str], dir_bytes: dict[str, int]
    ) -> None:
        """Warn once if a hot filesystem is mostly filled by non-cache data."""
        if self._shared_volume_warned:
            return
        for paths in self._group_dirs_by_device(hot_dirs).values():
            usage = self._disk_usage_bytes(paths[0])
            if usage is None or usage[0] <= 0:
                continue
            own_bytes = sum(dir_bytes.get(path, 0) for path in paths)
            if own_bytes < _SHARED_VOLUME_WARN_FRACTION * usage[0]:
                self._shared_volume_warned = True
                logger.warning(
                    "NIXL L3 cleaner: storage dirs %s hold %.2f GiB of the %.2f "
                    "GiB used on their filesystem. Cleanup watermarks apply to the "
                    "whole filesystem, so data outside the cache can keep "
                    "triggering deletion of the L3 cache. On a shared volume, set "
                    "l3_cleaner_capacity_gb to bound the cache's own usage instead.",
                    paths,
                    own_bytes / (1024**3),
                    usage[0] / (1024**3),
                )
                return

    def _scan_base_dir(self, base_dir: str, groups: dict[str, _GroupInfo]) -> int:
        """Add base_dir's objects to groups; return their total size in bytes."""
        if not os.path.isdir(base_dir):
            return 0
        try:
            bucket_entries = list(os.scandir(base_dir))
        except OSError:
            logger.warning("NIXL L3 cleaner failed to scan %s", base_dir, exc_info=True)
            return 0

        scanned_bytes = 0
        for bucket_entry in bucket_entries:
            try:
                is_bucket_dir = bucket_entry.is_dir(follow_symlinks=False)
            except OSError:
                continue
            if (
                not is_bucket_dir
                or _BUCKET_NAME_RE.fullmatch(bucket_entry.name) is None
            ):
                continue
            scanned_bytes += self._scan_bucket(base_dir, bucket_entry.path, groups)
        return scanned_bytes

    def _scan_bucket(
        self, base_dir: str, bucket_path: str, groups: dict[str, _GroupInfo]
    ) -> int:
        try:
            entries = list(os.scandir(bucket_path))
        except OSError:
            logger.debug(
                "NIXL L3 cleaner skipped bucket %s", bucket_path, exc_info=True
            )
            return 0

        scanned_bytes = 0
        for entry in entries:
            try:
                if not entry.is_file(follow_symlinks=False):
                    continue
                stat = entry.stat(follow_symlinks=False)
            except OSError:
                continue

            group_key = _parse_group_key(entry.name)
            group = groups.setdefault(group_key, _GroupInfo(group_key))
            group.paths.add(entry.path)
            group.base_dirs.add(base_dir)
            group.size += stat.st_size
            group.mtime = max(group.mtime, stat.st_mtime)
            scanned_bytes += stat.st_size
        return scanned_bytes

    def _iter_group_paths(self, groups: Iterable[_GroupInfo]) -> Iterable[str]:
        seen: set[str] = set()
        for group in groups:
            for path in sorted(group.paths):
                if path in seen:
                    continue
                seen.add(path)
                yield path
