# SPDX-License-Identifier: Apache-2.0
"""SANA-WM realtime interactive session — S3 backend.

The streaming denoising stage runs the whole clip in one call. For LIVE control
(WASD/IJKL keyboard between chunks) we need an *incremental* engine: a session
that holds the per-block KV cache + decoder conv-cache + latent state and exposes
``step(camera_conditions, chunk_plucker) -> latent_chunk`` (optionally decoded),
generating ONE chunk per user action. This is the "Design B" incremental loop —
the engine the websocket route + WASD/IJKL web UI drive.

Reuses the validated streaming pieces: ``forward_long`` (chunk-causal DiT),
``SanaWMStreamingDenoisingStage._accumulate_kv_cache`` / ``_autoregressive_segments``
(KV accumulator + chunk grid), the fresh ``FlowMatchEulerDiscreteScheduler(shift=1.0)``,
and (when a causal VAE is attached) ``AutoencoderKLCausalLTX2Video.decode_chunk``.
"""

from __future__ import annotations

from typing import Optional

import torch

from sglang.multimodal_gen.runtime.models.dits.sana_wm import _NUM_STREAM_CACHE_SLOTS
from sglang.multimodal_gen.runtime.models.schedulers.scheduling_flow_match_euler_discrete import (
    FlowMatchEulerDiscreteScheduler,
)
from sglang.multimodal_gen.runtime.pipelines_core.stages.model_specific_stages.sana_wm_streaming import (
    SanaWMStreamingDenoisingStage,
)


class SanaWMRealtimeSession:
    """Incremental, stateful streaming generator for interactive control.

    A new chunk is produced per ``step``; the recurrent GDN state / softmax
    concat-window / FFN tail (per-block KV cache) and the latent prefix carry
    across steps so a long video can be steered chunk-by-chunk in real time.
    """

    def __init__(
        self,
        transformer,
        *,
        denoising_step_list=(1000, 960, 889, 727, 0),
        num_frame_per_block: int = 3,
        num_cached_blocks: int = 2,
        sink_token: bool = True,
        cfg_scale: float = 1.0,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.bfloat16,
        vae=None,
    ) -> None:
        self.transformer = transformer
        self.vae = vae
        self.device = device or torch.device("cpu")
        self.dtype = dtype
        self.num_frame_per_block = int(num_frame_per_block)
        self.num_cached_blocks = int(num_cached_blocks)
        self.sink_token = bool(sink_token)
        self.cfg_scale = float(cfg_scale)
        self.use_cfg = self.cfg_scale > 1.0
        schedule = list(denoising_step_list)
        if len(schedule) < 2 or schedule[-1] != 0:
            raise ValueError(f"denoising_step_list must end with 0, got {schedule}")
        self._sigmas = [float(t) / 1000.0 for t in schedule[:-1]]
        self._scheduler = FlowMatchEulerDiscreteScheduler(shift=1.0)
        self.num_blocks = len(transformer.blocks)
        self._reset_state()

    def _reset_state(self) -> None:
        self.latents: Optional[torch.Tensor] = None  # (B, C, T_so_far, h, w)
        self.first_latent: Optional[torch.Tensor] = None
        self.pos_embeds = None
        self.neg_embeds = None
        self.pos_mask = None
        self.neg_mask = None
        # kv_cache[chunk_idx][block][slot]; grown per step.
        self.kv_cache: list = []
        self.chunk_indices: list[int] = [0]
        self.chunk_idx = 0

    @torch.no_grad()
    def reset(
        self,
        first_latent: torch.Tensor,
        pos_embeds: torch.Tensor,
        *,
        neg_embeds: Optional[torch.Tensor] = None,
        pos_mask: Optional[torch.Tensor] = None,
        neg_mask: Optional[torch.Tensor] = None,
    ) -> None:
        """Start a new clip. ``first_latent`` is the VAE-encoded first frame
        ``(B, C, 1, h, w)`` (the condition); ``pos_embeds`` the Gemma-2 prompt
        embeds. Subsequent frames are generated by ``step``."""
        self._reset_state()
        self.first_latent = first_latent.to(self.device, self.dtype)
        self.latents = self.first_latent.clone()
        self.pos_embeds = pos_embeds.to(self.device, self.dtype)
        self.neg_embeds = None if neg_embeds is None else neg_embeds.to(self.device, self.dtype)
        self.pos_mask = pos_mask
        self.neg_mask = neg_mask

    def _embeds_for_step(self):
        if self.use_cfg and self.neg_embeds is not None:
            embeds = torch.cat([self.neg_embeds, self.pos_embeds], dim=0)
            mask = (
                torch.cat([self.neg_mask, self.pos_mask], dim=0)
                if (self.pos_mask is not None and self.neg_mask is not None)
                else None
            )
        else:
            embeds, mask = self.pos_embeds, self.pos_mask
        return embeds, mask

    @torch.no_grad()
    def step(
        self,
        camera_conditions: Optional[torch.Tensor] = None,
        chunk_plucker: Optional[torch.Tensor] = None,
        *,
        n_frames: Optional[int] = None,
        decode: bool = False,
    ) -> torch.Tensor:
        """Generate the next chunk of ``n_frames`` latent frames.

        ``camera_conditions`` / ``chunk_plucker`` are this chunk's camera (e.g.
        from a WASD/IJKL action), sliced to the chunk's frames, on device. Returns
        the denoised latent chunk ``(B, C, n_frames, h, w)`` (or decoded pixels if
        ``decode`` and a causal VAE is attached). State advances in place.
        """
        if self.latents is None:
            raise RuntimeError("call reset() before step().")
        n = int(n_frames or self.num_frame_per_block)
        start_f = self.latents.shape[2] if self.chunk_idx > 0 else 0
        # Chunk 0 includes the conditioning first frame; later chunks are new.
        if self.chunk_idx == 0:
            chunk_frames = self.first_latent.shape[2] + n  # 1 (cond) + n
            end_f = chunk_frames
            noise = torch.randn(
                self.first_latent.shape[0], self.first_latent.shape[1], n,
                self.first_latent.shape[3], self.first_latent.shape[4],
                device=self.device, dtype=self.dtype,
            )
            chunk_lat = torch.cat([self.first_latent, noise], dim=2)
        else:
            end_f = start_f + n
            chunk_frames = n
            chunk_lat = torch.randn(
                self.latents.shape[0], self.latents.shape[1], n,
                self.latents.shape[3], self.latents.shape[4],
                device=self.device, dtype=self.dtype,
            )

        B, C = chunk_lat.shape[0], chunk_lat.shape[1]
        self.chunk_indices.append(end_f)
        self.kv_cache.append([[None] * _NUM_STREAM_CACHE_SLOTS for _ in range(self.num_blocks)])
        chunk_kv, sink_num = SanaWMStreamingDenoisingStage._accumulate_kv_cache(
            self.kv_cache, self.chunk_idx, self.chunk_indices,
            self.num_cached_blocks, self.sink_token, self.num_blocks,
        )
        frame_index = (
            torch.arange(start_f, end_f, device=self.device, dtype=torch.long)
            if sink_num > 0 else None
        )

        # Condition mask: the first frame of chunk 0 is the (fixed) condition.
        cond_mask = torch.zeros(B, C, chunk_frames, *chunk_lat.shape[3:], device=self.device, dtype=torch.float32)
        cond_local = []
        if self.chunk_idx == 0:
            cond_mask[:, :, 0] = 1.0
            cond_local = [0]
        init_chunk = chunk_lat.clone()

        embeds, mask = self._embeds_for_step()
        prope = (camera_conditions, chunk_plucker)
        self._scheduler.set_timesteps(sigmas=self._sigmas, device=self.device)
        for t in self._scheduler.timesteps:
            lat_in = torch.cat([chunk_lat, chunk_lat], dim=0) if self.use_cfg else chunk_lat
            ts = (1.0 - cond_mask) * t.to(self.device, torch.float32).view(1, 1, 1, 1, 1)
            ts_in = torch.cat([ts, ts], dim=0) if self.use_cfg else ts
            noise_pred, _ = self.transformer.forward_long(
                hidden_states=lat_in.to(self.dtype),
                encoder_hidden_states=embeds,
                timestep=ts_in[:, :1, :, 0, 0],
                encoder_attention_mask=mask,
                camera_conditions=camera_conditions,
                chunk_plucker=chunk_plucker,
                kv_cache=chunk_kv,
                save_kv_cache=False,
                start_f=start_f,
                end_f=end_f,
                frame_index=frame_index,
            )
            if self.use_cfg:
                nu, nt = noise_pred.chunk(2)
                noise_pred = nu + self.cfg_scale * (nt - nu)
            denoised = self._scheduler.step(
                -noise_pred.reshape(B, C, -1).transpose(1, 2),
                t,
                chunk_lat.reshape(B, C, -1).transpose(1, 2),
                per_token_timesteps=ts.reshape(B, C, -1)[:, 0],
                return_dict=False,
            )[0]
            chunk_lat = denoised.transpose(1, 2).reshape(init_chunk.shape).to(self.dtype)
            for loc in cond_local:
                chunk_lat[:, :, loc] = init_chunk[:, :, loc]

        # Clean t=0 pass to write this chunk's KV for the next step.
        ts_zero = torch.zeros(
            (2 if self.use_cfg else 1), 1, chunk_frames, device=self.device, dtype=torch.float32
        )
        lat_in = torch.cat([chunk_lat, chunk_lat], dim=0) if self.use_cfg else chunk_lat
        _, updated = self.transformer.forward_long(
            hidden_states=lat_in.to(self.dtype),
            encoder_hidden_states=embeds,
            timestep=ts_zero,
            encoder_attention_mask=mask,
            camera_conditions=camera_conditions,
            chunk_plucker=chunk_plucker,
            kv_cache=chunk_kv,
            save_kv_cache=True,
            start_f=start_f,
            end_f=end_f,
            frame_index=frame_index,
        )
        self.kv_cache[self.chunk_idx] = updated

        # Append to the running latent (chunk 0 already holds the first frame).
        if self.chunk_idx == 0:
            self.latents = chunk_lat
            new_frames = chunk_lat[:, :, 1:]
        else:
            self.latents = torch.cat([self.latents, chunk_lat], dim=2)
            new_frames = chunk_lat
        self.chunk_idx += 1

        if decode and self.vae is not None and hasattr(self.vae, "decode_chunk"):
            conv_cache = getattr(self, "_decoder_cache", None)
            if conv_cache is None:
                conv_cache = self.vae.reset_decoder_cache()
                self._decoder_cache = conv_cache
            return self.vae.decode_chunk(chunk_lat, conv_cache)
        return new_frames
