apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../minwm_tianpeng_gap12_same_host_h100_east2.yaml
patches:
  - path: delete-parity-pvc.yaml
  - path: job-source-ref.yaml
  - path: job-phx2.json
    target:
      group: batch
      version: v1
      kind: Job
      name: minwm-tianpeng-gap12-same-host-20260731-01
