name: "character_generation"
backend: "python"
input [
    {
        name: "INPUT_TEXT"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]
output [
    {
        name: "OUTPUT_TEXT"
        data_type: TYPE_STRING
        dims: [ -1 ]
    }
]
instance_group [
    {
        count: 1
        kind: KIND_GPU
        gpus: [ 0 ]
    }
]
