// NVIDIA/srt-slurm recipes curated for the Qwen3.5 cookbook.
// Keep this file as a single plain-data literal so Mintlify can hydrate it.

export const srtSlurmConfig = {
  repositoryUrl: "https://github.com/nvpohanh/srt-slurm-recipes",
  branch: "add-qwen35-gb300-agentic-sglang-recipes",
  recipesPath: "../srt-slurm-recipes",

  model: { id: "397b", label: "Qwen3.5-397B-A17B", subtitle: "FP8 / NVFP4" },
  hardware: { id: "gb300", label: "GB300", subtitle: "288GB · NVIDIA", gpusPerNode: 4 },

  workloads: [
    { id: "1k1k", label: "1K / 1K", subtitle: "input / output tokens" },
    { id: "8k1k", label: "8K / 1K", subtitle: "input / output tokens" },
    { id: "agentic", label: "Agentic", subtitle: "multi-turn coding" },
  ],
  strategies: [
    { id: "low-latency", label: "Low-Latency", subtitle: "fastest response" },
    { id: "balanced", label: "Balanced", subtitle: "mid-curve" },
    { id: "high-throughput", label: "High-Throughput", subtitle: "maximum scale" },
  ],

  recipes: [
    {
      workload: "1k1k",
      strategy: "low-latency",
      path: "recipes/multi-node/Qwen3.5/GB300/1k1k/sglang/disagg/fp8/stp/1p1d-tp4-tp4.yaml",
      prefillNodes: 1,
      decodeNodes: 1,
      description: "FP8 · TP4 prefill / TP4 decode",
      status: "pending",
    },
    {
      workload: "1k1k",
      strategy: "balanced",
      path: "recipes/multi-node/Qwen3.5/GB300/1k1k/sglang/disagg/fp8/stp/1p1d-dep4-dep16.yaml",
      prefillNodes: 1,
      decodeNodes: 4,
      description: "FP8 · DEP4 prefill / DEP16 decode",
      status: "pending",
    },
    {
      workload: "1k1k",
      strategy: "high-throughput",
      path: "recipes/multi-node/Qwen3.5/GB300/1k1k/sglang/disagg/fp8/stp/2p1d-dep4-dep16.yaml",
      prefillNodes: 2,
      decodeNodes: 4,
      description: "FP8 · two DEP4 prefill workers / one DEP16 decode worker",
      status: "pending",
    },
    {
      workload: "8k1k",
      strategy: "low-latency",
      path: "recipes/multi-node/Qwen3.5/GB300/8k1k/sglang/disagg/fp8/stp/1p1d-tp4-tp4.yaml",
      prefillNodes: 1,
      decodeNodes: 1,
      description: "FP8 · TP4 prefill / TP4 decode",
      status: "pending",
    },
    {
      workload: "8k1k",
      strategy: "balanced",
      path: "recipes/multi-node/Qwen3.5/GB300/8k1k/sglang/disagg/fp8/stp/4p1d-dep4-dep16.yaml",
      prefillNodes: 4,
      decodeNodes: 4,
      description: "FP8 · four DEP4 prefill workers / one DEP16 decode worker",
      status: "pending",
    },
    {
      workload: "8k1k",
      strategy: "high-throughput",
      path: "recipes/multi-node/Qwen3.5/GB300/8k1k/sglang/disagg/fp8/stp/8p1d-dep4-dep16.yaml",
      prefillNodes: 8,
      decodeNodes: 4,
      description: "FP8 · eight DEP4 prefill workers / one DEP16 decode worker",
      status: "pending",
    },
    {
      workload: "agentic",
      strategy: "low-latency",
      path: "recipes/multi-node/Qwen3.5/GB300/agentic/sglang/agg/mtp/agg-gb300-tp4-c1-mtp-hicache-jid2191933.yaml",
      servingNodes: 1,
      description: "NVFP4 · TP4 · concurrency 1 · MTP + HiCache",
      status: "pending",
      benchmark: {
        firstConcurrency: 1,
        concurrencyList: "1",
        resultFilename: "qwen35-agentic-low-latency",
        durationSeconds: 3600,
      },
    },
    {
      workload: "agentic",
      strategy: "balanced",
      path: "recipes/multi-node/Qwen3.5/GB300/agentic/sglang/disagg/mtp/disagg-gb300-2p1d-dep4-dep4-c192-mtp-hicache-convaware-jid2230562.yaml",
      prefillNodes: 2,
      decodeNodes: 1,
      infrastructureNodes: 1,
      description: "NVFP4 · DEP4 prefill / DEP4 decode · concurrency 192 · MTP + HiCache",
      status: "pending",
      benchmark: {
        firstConcurrency: 192,
        concurrencyList: "192",
        resultFilename: "qwen35-agentic-balanced",
        durationSeconds: 3600,
      },
    },
    {
      workload: "agentic",
      strategy: "high-throughput",
      path: "recipes/multi-node/Qwen3.5/GB300/agentic/sglang/disagg/mtp/disagg-gb300-4p1d-dep4-dep8-c384-mtp-hicache-convaware-jid2239740.yaml",
      prefillNodes: 4,
      decodeNodes: 2,
      infrastructureNodes: 1,
      description: "NVFP4 · DEP4 prefill / DEP8 decode · concurrency 384 · MTP + HiCache",
      status: "pending",
      benchmark: {
        firstConcurrency: 384,
        concurrencyList: "384",
        resultFilename: "qwen35-agentic-high-throughput",
        durationSeconds: 3600,
      },
    },
  ],
};
