// Official NVIDIA SRT Slurm recipes curated for the DeepSeek-V4 cookbook.
// Keep this file as a single plain-data literal so Mintlify can hydrate it.

export const srtSlurmConfig = {
  repositoryUrl: "https://github.com/NVIDIA/srt-slurm-recipes",
  branch: "main",
  recipesPath: "../srt-slurm-recipes",

  model: { id: "pro", label: "DeepSeek-V4-Pro", subtitle: "1.6T" },
  hardware: { id: "gb300", label: "GB300", subtitle: "288GB · NVIDIA", gpusPerNode: 4 },

  workloads: [
    { id: "1k1k", label: "1K / 1K", subtitle: "input / output tokens" },
    { id: "8k1k", label: "8K / 1K", subtitle: "input / output tokens" },
    { id: "agentic", label: "Agentic", subtitle: "multi-turn coding" },
  ],
  strategies: [
    { id: "low-latency", label: "Low-Latency", subtitle: "fastest response" },
    { id: "balanced", label: "Balanced", subtitle: "mid-curve" },
    { id: "high-throughput", label: "High-Throughput", subtitle: "maximum scale" },
  ],

  recipes: [
    {
      workload: "1k1k",
      strategy: "low-latency",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/1k1k/sglang/disagg/stp/disagg-1p1d-tp4-mxfp4.yaml",
      prefillNodes: 1,
      decodeNodes: 1,
      description: "TP4 prefill / TP4 decode",
    },
    {
      workload: "1k1k",
      strategy: "balanced",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/1k1k/sglang/disagg/stp/disagg-1p1d-dep4-mega-moe.yaml",
      prefillNodes: 1,
      decodeNodes: 1,
      description: "DEP4 with MegaMoE",
    },
    {
      workload: "1k1k",
      strategy: "high-throughput",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/1k1k/sglang/disagg/stp/disagg-1p2d-dep4-to-dep8-mega-moe.yaml",
      prefillNodes: 1,
      decodeNodes: 2,
      description: "DEP4 prefill / DEP8 decode with MegaMoE",
    },
    {
      workload: "8k1k",
      strategy: "low-latency",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/8k1k/sglang/disagg/disagg-low-latency-1p1d-tp4-tp4-mtp.yaml",
      prefillNodes: 1,
      decodeNodes: 1,
      description: "TP4 prefill / TP4 decode with MTP",
    },
    {
      workload: "8k1k",
      strategy: "balanced",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/8k1k/sglang/disagg/disagg-mid-curve-1p1d-dep4-dep8-mtp.yaml",
      prefillNodes: 1,
      decodeNodes: 2,
      description: "DEP4 prefill / DEP8 decode with MTP",
    },
    {
      workload: "8k1k",
      strategy: "high-throughput",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/8k1k/sglang/disagg/disagg-high-conc-8p1d-dep4-dep8-mtp.yaml",
      prefillNodes: 8,
      decodeNodes: 2,
      description: "high-concurrency DEP4 / DEP8 with MTP",
    },
    {
      workload: "agentic",
      strategy: "low-latency",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/agentic/sglang/agg/mtp/agg-gb300-tp4-mtp-kvoffload.yaml",
      servingNodes: 1,
      infrastructureNodes: 1,
      description: "TP4 · concurrency 1–16 · MTP + HiCache",
      repositoryUrl: "https://github.com/nvpohanh/srt-slurm-recipes",
      branch: "add-dsv4-gb300-agentic-sglang-recipes",
      status: "pending",
      benchmark: {
        firstConcurrency: 1,
        concurrencyList: "1 4 8 16",
        resultFilename: "dsv4-agentic-low-latency",
        durationSeconds: 3600,
      },
    },
    {
      workload: "agentic",
      strategy: "balanced",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/agentic/sglang/disagg/mtp/disagg-gb300-2p4d-dep8-dep16-c256-mtp-kvoffload.yaml",
      prefillNodes: 2,
      decodeNodes: 4,
      infrastructureNodes: 1,
      description: "DEP8 prefill / DEP16 decode · concurrency 256 · MTP + HiCache",
      repositoryUrl: "https://github.com/nvpohanh/srt-slurm-recipes",
      branch: "add-dsv4-gb300-agentic-sglang-recipes",
      status: "pending",
      benchmark: {
        firstConcurrency: 256,
        concurrencyList: "256",
        resultFilename: "dsv4-agentic-balanced",
        durationSeconds: 3600,
      },
    },
    {
      workload: "agentic",
      strategy: "high-throughput",
      path: "recipes/multi-node/DeepSeek-V4-Pro/GB300/agentic/sglang/disagg/mtp/disagg-gb300-12p4d-dep8-dep16-c1024-mtp-kvoffload.yaml",
      prefillNodes: 12,
      decodeNodes: 4,
      infrastructureNodes: 1,
      description: "DEP8 prefill / DEP16 decode · concurrency 1024 · MTP + HiCache",
      repositoryUrl: "https://github.com/nvpohanh/srt-slurm-recipes",
      branch: "add-dsv4-gb300-agentic-sglang-recipes",
      status: "pending",
      benchmark: {
        firstConcurrency: 1024,
        concurrencyList: "1024",
        resultFilename: "dsv4-agentic-high-throughput",
        durationSeconds: 3600,
      },
    },
  ],
};
