"""
FractalMesh Smart Contracts Agent v2.0.0
Generates EVM-compatible smart contract templates (ERC-20, payment split,
royalty distribution). Tracks deployment and manages on-chain state refs.
Samuel James Hiotis | ABN 56 628 117 363 | Sole Trader
"""
import os
import re
import time
import signal
import sqlite3
import hashlib
import json
from datetime import datetime

ROOT       = os.getenv("FRACTALMESH_HOME", os.path.expanduser("~/fmsaas"))
REPO       = os.getenv("REPO_ROOT",        os.path.expanduser("~/sglang"))
DB         = os.path.join(ROOT, "database", "sovereign.db")
DIST       = os.path.join(REPO, "fractalmesh", "dist")
INTERVAL   = int(os.getenv("SMART_CONTRACT_INTERVAL", "7200"))
DRY_RUN    = os.getenv("ENABLE_SMART_CONTRACTS", "false").lower() != "true"

OPERATOR   = "Samuel James Hiotis"
ABN        = "56 628 117 363"
PHI        = 1.6180339887

_running = True

# ── Contract templates ────────────────────────────────────────────────────────

def _erc20_template(name: str, symbol: str, total_supply: int,
                    owner_addr: str = "0x0000000000000000000000000000000000000001") -> str:
    return f"""// SPDX-License-Identifier: LicenseRef-FractalMesh-Sovereign
// Copyright (c) {datetime.utcnow().year} {OPERATOR} (ABN {ABN}) — Sole Trader
// Generated by FractalMesh Smart Contracts Agent v2.0.0
// WARNING: Review with a qualified Solidity auditor before deployment.

pragma solidity ^0.8.20;

contract {re.sub(r'[^A-Za-z0-9]', '', name)}Token {{
    string  public name     = "{name}";
    string  public symbol   = "{symbol}";
    uint8   public decimals = 18;
    uint256 public totalSupply;
    address public owner;

    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);

    constructor() {{
        owner       = {owner_addr};
        totalSupply = {total_supply} * 10**uint256(decimals);
        balanceOf[owner] = totalSupply;
        emit Transfer(address(0), owner, totalSupply);
    }}

    modifier onlyOwner() {{
        require(msg.sender == owner, "Not owner");
        _;
    }}

    function transfer(address to, uint256 value) external returns (bool) {{
        require(balanceOf[msg.sender] >= value, "Insufficient");
        balanceOf[msg.sender] -= value;
        balanceOf[to]         += value;
        emit Transfer(msg.sender, to, value);
        return true;
    }}

    function approve(address spender, uint256 value) external returns (bool) {{
        allowance[msg.sender][spender] = value;
        emit Approval(msg.sender, spender, value);
        return true;
    }}

    function transferFrom(address from, address to, uint256 value) external returns (bool) {{
        require(balanceOf[from] >= value, "Insufficient");
        require(allowance[from][msg.sender] >= value, "Allowance");
        balanceOf[from]              -= value;
        allowance[from][msg.sender]  -= value;
        balanceOf[to]                += value;
        emit Transfer(from, to, value);
        return true;
    }}
}}
"""


def _royalty_split_template(splits: list) -> str:
    """splits = [(address, bps)] where bps sum to 10000."""
    payees_init = "\n        ".join(
        f'payees.push({addr}); shares.push({bps});' for addr, bps in splits)
    total_bps = sum(bps for _, bps in splits)
    return f"""// SPDX-License-Identifier: LicenseRef-FractalMesh-Sovereign
// Copyright (c) {datetime.utcnow().year} {OPERATOR} (ABN {ABN}) — Sole Trader
// Royalty split: {total_bps} BPS total across {len(splits)} payees
// Generated by FractalMesh Smart Contracts Agent v2.0.0

pragma solidity ^0.8.20;

contract FractalRoyaltySplit {{
    address[] public payees;
    uint256[] public shares;   // basis points (1/100 of 1%)
    uint256   public totalBps;

    event PaymentReleased(address indexed payee, uint256 amount);

    constructor() {{
        {payees_init}
        totalBps = {total_bps};
    }}

    receive() external payable {{
        uint256 total = msg.value;
        for (uint i = 0; i < payees.length; i++) {{
            uint256 amt = (total * shares[i]) / totalBps;
            if (amt > 0) {{
                (bool ok,) = payees[i].call{{value: amt}}("");
                require(ok, "Transfer failed");
                emit PaymentReleased(payees[i], amt);
            }}
        }}
    }}
}}
"""


def _payment_link_template(recipient: str, amount_wei: int, memo: str) -> str:
    return f"""// SPDX-License-Identifier: LicenseRef-FractalMesh-Sovereign
// Simple payment forwarder — {memo}
// Generated by FractalMesh Smart Contracts Agent v2.0.0

pragma solidity ^0.8.20;

contract FractalPayment {{
    address payable public recipient = payable({recipient});
    uint256 public amount            = {amount_wei};
    string  public memo              = "{memo}";
    bool    public paid;

    event Paid(address indexed sender, uint256 amount);

    function pay() external payable {{
        require(!paid, "Already paid");
        require(msg.value >= amount, "Insufficient");
        paid = true;
        recipient.transfer(msg.value);
        emit Paid(msg.sender, msg.value);
    }}
}}
"""


# ── DB ────────────────────────────────────────────────────────────────────────

def _db_init():
    os.makedirs(os.path.dirname(DB), exist_ok=True)
    conn = sqlite3.connect(DB, timeout=10)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("""CREATE TABLE IF NOT EXISTS smart_contracts (
        id INTEGER PRIMARY KEY, contract_type TEXT, name TEXT,
        filename TEXT, source_hash TEXT UNIQUE, network TEXT DEFAULT 'undeployed',
        deployed_addr TEXT, phi_score REAL,
        ts DATETIME DEFAULT CURRENT_TIMESTAMP)""")
    conn.commit(); conn.close()


def _log_contract(ctype: str, name: str, filename: str,
                  src_hash: str, phi: float):
    conn = sqlite3.connect(DB, timeout=10)
    try:
        conn.execute("""INSERT INTO smart_contracts
            (contract_type,name,filename,source_hash,phi_score)
            VALUES (?,?,?,?,?)""",
            (ctype, name, filename, src_hash, phi))
        conn.commit()
    except sqlite3.IntegrityError:
        pass
    finally:
        conn.close()


def _write_contract(filename: str, source: str) -> str:
    os.makedirs(DIST, exist_ok=True)
    path = os.path.join(DIST, filename)
    if not DRY_RUN:
        with open(path, "w") as f:
            f.write(source)
    return hashlib.sha256(source.encode()).hexdigest()[:16]


def run_cycle():
    ts = datetime.utcnow().isoformat()
    print(f"[fm-smart-contracts] {ts} | dry={DRY_RUN}")

    contracts = [
        # (type, name, symbol, supply, filename)
        ("erc20", "FractalMesh Token",    "FMT",   1_000_000,
         "FractalMeshToken.sol"),
        ("erc20", "Sovereign Node Token", "SNOD",  10_000_000,
         "SovereignNodeToken.sol"),
    ]

    for ctype, name, symbol, supply, fname in contracts:
        src   = _erc20_template(name, symbol, supply)
        shash = _write_contract(fname, src)
        phi   = round(supply / 1_000_000 * PHI, 4)
        _log_contract(ctype, name, fname, shash, phi)
        print(f"   [{ctype}] {name} ({symbol}) → {fname} | hash={shash} | dry={DRY_RUN}")

    # Royalty split (5 pools: operator 60%, reinvest 20%, compliance 10%, DePIN 5%, bounty 5%)
    # Placeholder addresses — fill with real wallets before deploying
    splits = [
        ("0x0000000000000000000000000000000000000001", 6000),
        ("0x0000000000000000000000000000000000000002", 2000),
        ("0x0000000000000000000000000000000000000003", 1000),
        ("0x0000000000000000000000000000000000000004",  500),
        ("0x0000000000000000000000000000000000000005",  500),
    ]
    src   = _royalty_split_template(splits)
    shash = _write_contract("FractalRoyaltySplit.sol", src)
    _log_contract("royalty_split", "FractalMesh Royalty Split",
                  "FractalRoyaltySplit.sol", shash, round(PHI ** 3, 4))
    print(f"   [royalty_split] FractalRoyaltySplit.sol | hash={shash}")

    # Payment link contract for 4A Audit tier ($750 AUD ≈ 0.2 ETH placeholder)
    src   = _payment_link_template(
        "0x0000000000000000000000000000000000000001",
        200_000_000_000_000_000,  # 0.2 ETH in wei
        "FractalMesh Infrastructure Audit — Samuel James Hiotis ABN 56628117363")
    shash = _write_contract("FractalPaymentAudit.sol", src)
    _log_contract("payment", "4A Audit Payment",
                  "FractalPaymentAudit.sol", shash, round(PHI, 4))
    print(f"   [payment] FractalPaymentAudit.sol | hash={shash}")
    print(f"   NOTE: Review all contracts with a Solidity auditor before deployment")


def _sigterm(s, f):
    global _running
    _running = False


if __name__ == "__main__":
    signal.signal(signal.SIGTERM, _sigterm)
    signal.signal(signal.SIGINT,  _sigterm)
    _db_init()
    print(f"[fm-smart-contracts] Active | interval={INTERVAL}s | dry={DRY_RUN}")
    while _running:
        try:
            run_cycle()
        except Exception as e:
            print(f"[fm-smart-contracts] ERR {e}")
        for _ in range(INTERVAL):
            if not _running: break
            time.sleep(1)
    print("[fm-smart-contracts] Stopped.")
