#!/usr/bin/env python3
"""Generate Bazel-facing dependency profile files from SGLang pyprojects."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]

PROFILES = {
    "cuda": "pyproject.toml",
    "cpu": "pyproject_cpu.toml",
    "npu": "pyproject_npu.toml",
    "xpu": "pyproject_xpu.toml",
    "other": "pyproject_other.toml",
}

SYSTEM_DEP_NAMES = {
    "cuda-python",
    "deep-gemm",
    "flash-attn-3",
    "flash-attn-4",
    "flashinfer-cubin",
    "flashinfer-python",
    "kernels",
    "mthreads-ml-py",
    "nvidia-cutlass-dsl",
    "petit-kernel",
    "quack-kernels",
    "sgl-kernel",
    "sglang-kernel",
    "smg-grpc-servicer",
    "torch",
    "torch-musa",
    "torch-memory-saver",
    "torchao",
    "torchaudio",
    "torchcodec",
    "torchvision",
    "triton",
    "wave-lang",
}


def _canonical_name(requirement: str) -> str:
    match = re.match(r"\s*([A-Za-z0-9_.-]+)", requirement)
    if not match:
        raise ValueError(f"cannot parse requirement name: {requirement!r}")
    return re.sub(r"[-_.]+", "-", match.group(1)).lower()


def _is_system_dep(requirement: str) -> bool:
    return _canonical_name(requirement) in SYSTEM_DEP_NAMES


def _load_pyproject(profile: str) -> dict[str, Any]:
    pyproject = REPO_ROOT / "python" / PROFILES[profile]
    with pyproject.open("rb") as f:
        return tomllib.load(f)


def _profile_metadata(profile: str) -> dict[str, Any]:
    data = _load_pyproject(profile)
    project = data["project"]
    setuptools = data.get("tool", {}).get("setuptools", {})
    return {
        "profile": profile,
        "source": f"python/{PROFILES[profile]}",
        "project_name": project["name"],
        "dependencies": project.get("dependencies", []),
        "optional_dependencies": project.get("optional-dependencies", {}),
        "scripts": project.get("scripts", {}),
        "package_data": setuptools.get("package-data", {}),
    }


def _starlark_list(items: list[str], indent: str = "    ") -> str:
    if not items:
        return "[]"
    values = [f'{indent}"{item}",' for item in items]
    return "[\n" + "\n".join(values) + "\n]"


def _starlark_dict_of_lists(items: dict[str, list[str]]) -> str:
    if not items:
        return "{}"
    lines = ["{"]
    for key, values in items.items():
        lines.append(f'    "{key}": {_starlark_list(values, indent="        ")},')
    lines.append("}")
    return "\n".join(lines)


def _starlark_dict(items: dict[str, Any]) -> str:
    if not items:
        return "{}"
    lines = ["{"]
    for key, value in items.items():
        lines.append(f'    "{key}": "{value}",')
    lines.append("}")
    return "\n".join(lines)


def _render_bzl(meta: dict[str, Any]) -> str:
    dependencies = meta["dependencies"]
    system_deps = [dep for dep in dependencies if _is_system_dep(dep)]
    managed_deps = [dep for dep in dependencies if not _is_system_dep(dep)]
    return "\n".join(
        [
            '"""Generated dependency metadata for the SGLang Bazel overlay."""',
            "",
            "# Generated by tools/bazel/gen_deps.py. Do not edit.",
            f'PROFILE = "{meta["profile"]}"',
            f'SOURCE = "{meta["source"]}"',
            f'PROJECT_NAME = "{meta["project_name"]}"',
            "",
            "DEPENDENCIES = " + _starlark_list(dependencies),
            "",
            "BAZEL_MANAGED_DEPS = " + _starlark_list(managed_deps),
            "",
            "BAZEL_SYSTEM_DEPS = " + _starlark_list(system_deps),
            "",
            "OPTIONAL_DEPENDENCIES = "
            + _starlark_dict_of_lists(meta["optional_dependencies"]),
            "",
            "SCRIPTS = " + _starlark_dict(meta["scripts"]),
            "",
            "PACKAGE_DATA = " + _starlark_dict_of_lists(meta["package_data"]),
            "",
        ]
    )


def _outputs_for(profile: str) -> dict[Path, str]:
    meta = _profile_metadata(profile)
    return {
        REPO_ROOT / "tools" / "bazel" / f"deps_{profile}.bzl": _render_bzl(meta),
    }


def _write_outputs() -> None:
    for profile in PROFILES:
        for path, content in _outputs_for(profile).items():
            path.write_text(content)


def _check_outputs() -> int:
    exit_code = 0
    for profile in PROFILES:
        for path, expected in _outputs_for(profile).items():
            actual = path.read_text() if path.exists() else ""
            if actual != expected:
                exit_code = 1
                sys.stderr.writelines(
                    difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        expected.splitlines(keepends=True),
                        fromfile=str(path),
                        tofile=f"{path} (expected)",
                    )
                )
    return exit_code


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return _check_outputs()
    _write_outputs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
