"""
IOChain core abstractions — IOProcessor, IOContext, IOChain.

This module has no dependency on any SGLang serving or inference code and
can be imported standalone.

Architecture
------------
The pipeline sits between the HTTP layer and the inference engine:

    HTTP request
        │
        ▼
    tokenisation  (TokenizerManager)
        │
        ▼
    IOChain.run_ingress(ctx)          ← processors run 0 → N
        │
        ▼
    inference  (SGLang engine)
        │
        ▼
    IOChain.run_egress(ctx)           ← processors run N → 0
        │
        ▼
    HTTP response

Each processor sees the same ``IOContext`` object for both phases, so state
accumulated during ingress (e.g. a request timestamp or a parsed field) is
available during egress without external storage.

Processor modes
---------------
``blocking = True``  (default)
    The coroutine is awaited inline.  Any exception propagates to the caller
    and aborts the request.  Use this for processors that *must* succeed
    before inference proceeds — auth checks, PII redaction, rate limiting.

``blocking = False``
    The coroutine is scheduled as ``asyncio.create_task``; the calling task
    continues immediately.  Exceptions are caught and logged; they never
    crash the request.  Use this for side-effects that should not affect
    latency — logging, metrics, audit trails.

Streaming responses
-------------------
``ctx.response`` is ``None`` for streaming requests because individual SSE
chunks are not buffered.  The egress hook still fires (via
``_wrap_streaming_egress``) after the last chunk is sent.  Guard any
response-field access with ``if ctx.response is not None``.
"""

from __future__ import annotations

import asyncio
import logging
import time
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class IOContext:
    """
    Carries request/response data through the processor pipeline for one request.

    Attributes
    ----------
    request_id:
        Unique hex string generated by ``IOChain.make_context``.
    raw_request:
        The original OpenAI-protocol request object (e.g. ``ChatCompletionRequest``).
    adapted_request:
        The internal ``GenerateReqInput`` produced after tokenisation.
    response:
        Set to the response object on egress for non-streaming requests.
        ``None`` during ingress and for all streaming requests.
    metadata:
        Free-form dict for processors to pass state between ingress and egress
        without subclassing or external storage.
    start_time:
        ``time.monotonic()`` timestamp captured when the context is created,
        used to compute end-to-end latency in egress processors.
    """

    request_id: str
    raw_request: Any       # OpenAI-protocol request object
    adapted_request: Any   # Internal GenerateReqInput (after tokenisation)
    response: Any = None   # Set on egress; None during ingress and for streaming
    metadata: dict = field(default_factory=dict)
    start_time: float = field(default_factory=time.monotonic)


class IOProcessor(ABC):
    """
    Abstract base class for a single pipeline stage.

    Subclass this and implement ``on_request`` and ``on_response``.  Set the
    ``blocking`` class attribute to control execution semantics:

    ``blocking = True``  (default)
        Awaited inline before inference proceeds.  Exceptions propagate to the
        HTTP caller as a 500 error.  Use for: authentication, rate limiting,
        input validation, PII scrubbing.

    ``blocking = False``
        Scheduled as ``asyncio.create_task``; the request continues without
        waiting.  Exceptions are logged and swallowed.  Use for: request
        logging, metrics emission, async audit trails.

    Example
    -------
    ::

        class TokenBudgetGuard(IOProcessor):
            blocking = True  # block the request if over budget

            async def on_request(self, ctx: IOContext) -> None:
                tokens = count_tokens(ctx.raw_request)
                if tokens > DAILY_LIMIT:
                    raise HTTPException(status_code=429, detail="token budget exceeded")
                ctx.metadata["token_count"] = tokens

            async def on_response(self, ctx: IOContext) -> None:
                deduct(ctx.metadata["token_count"])
    """

    blocking: bool = True

    @abstractmethod
    async def on_request(self, ctx: IOContext) -> None:
        """
        Ingress hook — called after tokenisation, before inference.

        Raise any exception to abort the request (blocking processors only).
        Store state needed during egress in ``ctx.metadata``.
        """

    @abstractmethod
    async def on_response(self, ctx: IOContext) -> None:
        """
        Egress hook — called after the response is fully delivered.

        For streaming requests ``ctx.response`` is ``None`` (individual chunks
        are not buffered).  Guard response-field access with::

            if ctx.response is not None:
                ...
        """


async def _run_safe(coro: Any, processor_name: str, phase: str) -> None:
    """Await *coro*, logging any exception without re-raising (non-blocking path)."""
    try:
        await coro
    except Exception:
        logger.exception("IOChain %s processor %s raised", phase, processor_name)


class IOChain:
    """
    Ordered pipeline of ``IOProcessor`` instances.

    Processors are added with ``add()`` and executed in two passes:

    * **Ingress** (``run_ingress``): insertion order, 0 → N.
      Runs after tokenisation, before the inference engine is called.
    * **Egress** (``run_egress``): reverse order, N → 0.
      Runs after the response is fully delivered (or, for streaming, after
      the last SSE chunk).

    The symmetric reverse-egress ordering means processors naturally unwrap
    in stack order, which is convenient for paired operations such as
    request/response logging, span open/close, or lock acquire/release.

    Usage
    -----
    ::

        chain = IOChain()
        chain.add(AuthProcessor()).add(RequestLoggingProcessor())

        # In the serving layer:
        ctx = chain.make_context(raw_request, adapted_request)
        await chain.run_ingress(ctx)
        # ... inference ...
        ctx.response = response
        await chain.run_egress(ctx)
    """

    def __init__(self) -> None:
        self._processors: list[IOProcessor] = []

    def add(self, p: IOProcessor) -> "IOChain":
        """Append *p* to the pipeline; returns ``self`` for fluent chaining."""
        self._processors.append(p)
        return self

    def make_context(self, raw_request: Any, adapted_request: Any) -> IOContext:
        """Create a fresh ``IOContext`` with a unique request ID."""
        return IOContext(
            request_id=uuid.uuid4().hex,
            raw_request=raw_request,
            adapted_request=adapted_request,
        )

    async def run_ingress(self, ctx: IOContext) -> None:
        """
        Execute the ingress phase for all processors in insertion order.

        Blocking processors are awaited inline; a raised exception aborts the
        loop and propagates to the caller.  Non-blocking processors are
        fire-and-forget via ``asyncio.create_task``.
        """
        for p in self._processors:
            if p.blocking:
                await p.on_request(ctx)
            else:
                asyncio.create_task(
                    _run_safe(p.on_request(ctx), type(p).__name__, "ingress")
                )

    async def run_egress(self, ctx: IOContext) -> None:
        """
        Execute the egress phase for all processors in reverse order.

        Same blocking/non-blocking semantics as ``run_ingress``.
        """
        for p in reversed(self._processors):
            if p.blocking:
                await p.on_response(ctx)
            else:
                asyncio.create_task(
                    _run_safe(p.on_response(ctx), type(p).__name__, "egress")
                )
