// COMMUNITY half of the SGLang cookbook. A small section at the BOTTOM of a model page
// that features community deployment work: the config as contributed, and a link to the
// contribution. Nothing else.
//
// Why a card list and not more matrix cells: the Deploy matrix is a cross-product, so
// one contributed hardware id multiplies every quant × strategy × nodes and leaves a
// row of greyed-out combinations behind it. A contribution costs one group. It also
// keeps `supportedHardware` / `quantizations` / the Playground knob-gating — and the
// green "Verified" badge — reserved for what the team has actually reproduced.
//
// The unit is a CONTRIBUTION (one PR), not a config, because a single PR routinely adds
// several configs (low-latency / balanced / high-throughput) and a reader browsing
// community work wants them together under the credit and the link they came from.
//
// Layout is a horizontal CAROUSEL, so N contributions cost the height of one — stacking
// them made the section dominate the page bottom. Within a contribution, several configs
// are chips. Two levels, both fixed-height:
//
//   carousel  ‹ ●━● › 2/3        one contribution per slide, auto-advancing every 5s
//     chips   [low-latency] [balanced]      one config shown at a time
//
// Autoplay rules, because these slides hold a command a reader may be mid-copy of:
// hover/focus pauses, ANY manual interaction (arrow, dot, chip, run-mode, Copy) stops it
// permanently for the session, a deep link stops it, and `prefers-reduced-motion`
// disables it outright. Slides stay mounted and move by translateX rather than being
// conditionally rendered, which keeps the track height stable and keeps every
// `#community-<id>` anchor in the DOM for deep links to resolve against.
//
// Deliberately NOT here: benchmark numbers, editorial notes, trust badges, status
// taxonomies, per-claim attribution tags. Earlier drafts had all of it, and every layer
// made the section read as a second, weaker deployment matrix. It shows the config and
// links the PR. Measurements, caveats, and review all live in the PR, one click away —
// and a community measurement taken in the contributor's own workload was never
// comparable to the matrix cards anyway, so rendering it beside them invited exactly the
// wrong comparison.
//
// Data comes from a per-model `configs/<org>/<model>-community.jsx` exporting
// `community: Contribution[]`, GENERATED by docs/scripts/gen_community_entry.mjs:
//
//   source       {label, url, author, org?, authorUrl?} — the PR and who wrote it
//   reportedAt   optional ISO date (the PR's last-updated day)
//   configs      Config[] — every config the PR contributed
//
// and each Config:
//
//   id             URL-anchor slug, unique across the file
//   title          short label, also the chip text when a PR has several configs
//   hardware       FREE TEXT for the GPU MODEL ONLY, e.g. "NVIDIA H20 (96GB)".
//                  Deliberately NOT a HARDWARE_CATALOG id: community hardware must
//                  never require an engine-catalog edit or add a chip to the Deploy
//                  selector. Do NOT bake a count in ("8× …") — the count is derived
//                  from --tp × --nnodes, and a hand-typed one silently goes stale
//   modelName      HF slug, substituted for {{MODEL_NAME}}
//   sglangVersion  the version/tag/SHA the contributor tested
//   dockerImage    optional — enables the Docker output tab
//   env, flags     rendered VERBATIM, only {{PLACEHOLDER}} substitution applied
//
// There is no `summary` and no `editorNotes`: the knob line under a title is COMPUTED
// from `flags` by describeFlags(), so it cannot drift from the command it describes.
//
// Optional `config` prop: only used to read placeholder defaults so HOST_IP / PORT match
// whatever the reader set in the Deploy panel's Env dialog (same localStorage key).
//
// Mintlify caveats this file routes around (same as _deployment.jsx):
//   - Module-level statements are stripped — everything lives inside the wrapper.
//   - Capitalized JSX tags get rebound by _provideComponents() — lowercase HTML only.
//   - Snippets cannot import each other; config arrives as a prop from the MDX.

export const CommunityConfigs = ({ community, config }) => {
  // ==== 1. Style helper (dark-mode-aware) ====
  // Left border is violet, so the section reads as a third surface at a glance:
  // Deploy is red (#D45D44), Playground amber (#FB923C), Community violet.
  const makeStyles = (isDark) => ({
    container: {
      maxWidth: "900px", margin: "0 auto",
      display: "flex", flexDirection: "column", gap: "8px",
    },
    group: {
      border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
      borderLeft: `3px solid ${isDark ? "#A78BFA" : "#8B5CF6"}`,
      borderRadius: "4px",
      background: isDark ? "#1f2937" : "#fff",
      padding: "8px 12px",
      display: "flex", flexDirection: "column", gap: "6px",
      // Every card is the same box: full slide width, and stretched to the tallest
      // slide's height by the track's default `align-items: stretch`. Without `flex: 1`
      // the card would size to its own content inside an already-stretched slide, so
      // cards would visibly differ in height as the carousel advances.
      flex: 1, minWidth: 0, width: "100%", boxSizing: "border-box",
    },
    // Credit and the PR link sit at the TOP of a group: the point of the section is to
    // feature the work, so the attribution leads rather than trailing in a footer.
    groupHead: {
      display: "flex", flexWrap: "wrap", alignItems: "baseline",
      justifyContent: "space-between", gap: "4px 10px",
    },
    who: {
      fontSize: "12px", fontWeight: 600,
      color: isDark ? "#e5e7eb" : "#111827",
    },
    whoMeta: {
      fontSize: "11px", fontWeight: 400,
      color: isDark ? "#9ca3af" : "#6b7280",
    },
    prLink: {
      fontSize: "11px", fontWeight: 600, flexShrink: 0,
      color: isDark ? "#C4B5FD" : "#6D28D9",
      textDecoration: "underline", textUnderlineOffset: "2px",
    },
    chipRow: { display: "flex", flexWrap: "wrap", gap: "4px" },
    chip: (active) => ({
      padding: "2px 10px", fontSize: "11px", fontWeight: 500, cursor: "pointer",
      borderRadius: "3px",
      border: `1px solid ${active ? "#8B5CF6" : (isDark ? "#4b5563" : "#d1d5db")}`,
      background: active ? "#8B5CF6" : (isDark ? "#1f2937" : "#fff"),
      color: active ? "#fff" : (isDark ? "#e5e7eb" : "#374151"),
      userSelect: "none",
    }),
    identity: {
      display: "flex", flexWrap: "wrap", alignItems: "center", gap: "2px 6px",
      fontSize: "11px", color: isDark ? "#9ca3af" : "#6b7280",
    },
    knobs: {
      fontSize: "11px", lineHeight: "1.4",
      color: isDark ? "#9ca3af" : "#6b7280",
    },
    commandWrap: {
      background: isDark ? "#111827" : "#f5f5f5",
      borderRadius: "6px",
      border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
      overflow: "hidden",
    },
    commandHeader: {
      display: "flex", flexWrap: "wrap", justifyContent: "space-between",
      alignItems: "center", gap: "6px 10px",
      padding: "6px 10px",
      borderBottom: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
      background: isDark ? "#1f2937" : "#fafafa",
    },
    commandPre: {
      padding: "12px 16px",
      fontFamily: "'Menlo', 'Monaco', 'Courier New', monospace",
      fontSize: "12px", lineHeight: "1.5",
      color: isDark ? "#e5e7eb" : "#374151",
      whiteSpace: "pre-wrap", overflowX: "auto", margin: 0,
      // Sized to fit the longest realistic config outright (~16 flags ≈ 300px); only a
      // pathological command scrolls internally. This is the backstop that keeps the
      // uniform card height — set by the tallest slide — from running away.
      maxHeight: "420px", overflowY: "auto",
    },
    // ---- carousel ----
    viewport: { overflow: "hidden" },
    track: (slide, animate) => ({
      display: "flex",
      transform: `translateX(-${slide * 100}%)`,
      transition: animate ? "transform 0.4s ease" : "none",
    }),
    // `display: flex` so the card inside can stretch to the slide's full height; the
    // track stretches every slide to the tallest one, so all cards end up identical.
    slide: { flex: "0 0 100%", minWidth: 0, display: "flex" },
    nav: {
      display: "flex", alignItems: "center", justifyContent: "center", gap: "8px",
      paddingTop: "2px",
    },
    navBtn: {
      padding: "1px 8px", lineHeight: 1.3,
      border: `1px solid ${isDark ? "#4b5563" : "#d1d5db"}`,
      borderRadius: "4px",
      background: isDark ? "#1f2937" : "#fff",
      color: isDark ? "#e5e7eb" : "#374151",
      fontSize: "13px", cursor: "pointer",
    },
    dot: (active) => ({
      width: active ? "18px" : "6px", height: "6px", borderRadius: "3px",
      background: active ? "#8B5CF6" : (isDark ? "#4b5563" : "#d1d5db"),
      cursor: "pointer", transition: "width 0.2s, background 0.2s",
    }),
    navCount: {
      fontSize: "10px", color: isDark ? "#6b7280" : "#9ca3af",
      fontVariantNumeric: "tabular-nums", minWidth: "56px", textAlign: "right",
    },
    iconButton: {
      padding: "4px 10px",
      border: `1px solid ${isDark ? "#4b5563" : "#d1d5db"}`,
      borderRadius: "4px",
      background: isDark ? "#1f2937" : "#fff",
      color: isDark ? "#e5e7eb" : "#374151",
      fontSize: "11px", fontWeight: 500, cursor: "pointer",
      display: "inline-flex", alignItems: "center", gap: "4px",
    },
    runModeWrap: {
      display: "inline-flex",
      border: `1px solid ${isDark ? "#4b5563" : "#d1d5db"}`,
      borderRadius: "10px", overflow: "hidden",
      fontSize: "11px", fontWeight: 600, userSelect: "none",
    },
    runModeChip: (active, last) => ({
      padding: "2px 10px", cursor: "pointer",
      background: active ? (isDark ? "#1f2937" : "#fff") : "transparent",
      color: active
        ? (isDark ? "#e5e7eb" : "#111827")
        : (isDark ? "#9ca3af" : "#6b7280"),
      ...(last ? {} : { borderRight: `1px solid ${isDark ? "#4b5563" : "#d1d5db"}` }),
    }),
    empty: {
      padding: "12px", borderRadius: "4px", fontSize: "12px",
      color: isDark ? "#9ca3af" : "#6b7280",
      border: `1px dashed ${isDark ? "#374151" : "#e5e7eb"}`,
    },
    cta: {
      padding: "2px 12px", fontSize: "12px",
      color: isDark ? "#9ca3af" : "#6b7280",
      display: "flex", flexWrap: "wrap", alignItems: "center", gap: "6px",
    },
    ctaButton: {
      background: "transparent", border: "none", padding: 0,
      color: isDark ? "#C4B5FD" : "#6D28D9",
      cursor: "pointer", fontSize: "12px", fontWeight: 600,
      textDecoration: "underline", textUnderlineOffset: "2px",
    },
  });

  // ==== 2. Pure helpers ====
  // Everything the card SAYS about a recipe is derived from `flags`. There is no
  // hand-written summary field on purpose: prose drifts from the command the moment
  // someone edits one and not the other, and a reader cannot tell which is wrong.
  const flagValue = (flags, name) => {
    for (const f of flags || []) {
      const parts = f.trim().split(/[\s=]+/);
      if (parts[0] === name) return parts.length > 1 ? parts.slice(1).join(" ") : true;
    }
    return undefined;
  };
  const flagInt = (flags, name, dflt) => {
    const n = parseInt(flagValue(flags, name), 10);
    return Number.isFinite(n) ? n : dflt;
  };

  // GPU count = tp × nnodes. An absent --tp means tp=1 — sglang's actual default — NOT
  // 8: a model that fits on one GPU legitimately ships without the flag, and assuming a
  // full node would overstate the deployment by 8×.
  const gpuCountOf = (flags) =>
    flagInt(flags, "--tp", flagInt(flags, "--tp-size", 1)) * flagInt(flags, "--nnodes", 1);

  // The recipe's distinguishing knobs, in a fixed order so two configs are comparable.
  const describeFlags = (flags) => {
    const parts = [];
    const str = (name) => {
      const v = flagValue(flags, name);
      return typeof v === "string" ? v : null;
    };
    const quant = str("--quantization");
    if (quant) parts.push(quant.toUpperCase());
    const specAlgo = str("--speculative-algorithm");
    if (specAlgo) {
      const triple = [
        str("--speculative-num-steps"),
        str("--speculative-eagle-topk"),
        str("--speculative-num-draft-tokens"),
      ];
      parts.push(specAlgo + (triple.every(Boolean) ? ` ${triple.join("-")}` : ""));
    }
    if (flagValue(flags, "--enable-prefill-cp")) {
      const cp = str("--attn-cp-size");
      parts.push("prefill CP" + (cp || ""));
    }
    if (flagValue(flags, "--enable-dp-attention")) {
      const dp = str("--dp") || str("--dp-size");
      parts.push("DP attention" + (dp ? ` ${dp}` : ""));
    }
    if (flagValue(flags, "--enable-ep-moe")) parts.push("EP MoE");
    const mfs = str("--mem-fraction-static");
    if (mfs) parts.push(`mem-fraction ${mfs}`);
    const mrr = str("--max-running-requests");
    if (mrr) parts.push(`max-running ${mrr}`);
    const cpfs = str("--chunked-prefill-size");
    if (cpfs) parts.push(`chunked-prefill ${cpfs}`);
    return parts;
  };

  const PLACEHOLDER_FALLBACKS = { HOST_IP: "0.0.0.0", PORT: "30000" };

  const placeholderDefaults = (schema) => {
    const out = { ...PLACEHOLDER_FALLBACKS };
    for (const [key, spec] of Object.entries(schema || {})) {
      if (spec && spec.default != null) out[key] = spec.default;
    }
    return out;
  };

  const interpolate = (text, envValues, modelName) =>
    (text || "").replace(/\{\{(\w+)\}\}/g, (m, key) => {
      if (key === "MODEL_NAME") return modelName || m;
      return envValues[key] != null && envValues[key] !== "" ? envValues[key] : m;
    });

  // Command rendering is intentionally a SIMPLIFIED cousin of _deployment.jsx's: flags
  // and env are literals, so there is no overlay composition, no multi-node flag
  // splicing, and no PD port rewrite. A community config needing those belongs in the
  // matrix, not here.
  const renderCommand = (cfg, envValues, mode) => {
    const flags = cfg.flags || [];
    const env = cfg.env || [];
    if (mode === "docker") {
      const image = cfg.dockerImage || "lmsysorg/sglang:latest";
      const portFlag = flags.find((f) => f.split(/[\s=]/)[0] === "--port");
      const servePort = portFlag ? portFlag.slice("--port".length).trim() : "{{PORT}}";
      return interpolate([
        "docker run --gpus all",
        "  --shm-size 32g",
        `  -p ${servePort}:${servePort}`,
        "  -v ~/.cache/huggingface:/root/.cache/huggingface",
        ...env.map((e) => `  --env ${e}`),
        "  --ipc=host",
        `  ${image}`,
        "  sglang serve",
        ...flags.map((f) => "    " + f),
      ].join(" \\\n"), envValues, cfg.modelName);
    }
    const envBlock = env.length ? env.join(" \\\n") + " \\\n" : "";
    return interpolate(
      `${envBlock}sglang serve \\\n${flags.map((f) => "  " + f).join(" \\\n")}`,
      envValues, cfg.modelName);
  };

  // ==== 3. React state + effects ====
  const [isDark, setIsDark] = useState(false);
  useEffect(() => {
    const check = () => {
      const html = document.documentElement;
      setIsDark(
        html.classList.contains("dark") ||
          html.getAttribute("data-theme") === "dark" ||
          html.style.colorScheme === "dark"
      );
    };
    check();
    const observer = new MutationObserver(check);
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class", "data-theme", "style"],
    });
    return () => observer.disconnect();
  }, []);

  // Same localStorage key the Deploy panel's Env dialog writes, so HOST_IP / PORT agree
  // across the page. Read-only here — this section has no Env UI.
  const [env, setEnv] = useState(() => placeholderDefaults(config && config.placeholders));
  useEffect(() => {
    try {
      const raw = window.localStorage.getItem("sglang-deploy-env");
      if (raw) {
        setEnv({
          ...placeholderDefaults(config && config.placeholders),
          ...JSON.parse(raw),
        });
      }
    } catch {}
  }, []);

  const groups = community || [];
  // Which config is selected within each contribution, keyed by the PR label.
  const [picked, setPicked] = useState({});
  const [runModes, setRunModes] = useState({});
  const [copiedId, setCopiedId] = useState(null);

  // ---- carousel: one contribution visible at a time ----
  const [slide, setSlide] = useState(0);
  // Hover pauses; `stopped` is permanent. Autoplay that keeps fighting a reader is worse
  // than no autoplay: these panels hold a command someone may be halfway through
  // copying, so ANY manual interaction (arrow, dot, chip, Copy, Python/Docker) ends it
  // for the session rather than merely deferring it.
  const [hovering, setHovering] = useState(false);
  const [stopped, setStopped] = useState(false);
  // Suppress the slide transition for the initial deep-link jump, so a linked config
  // does not animate in from across the track on load.
  const [animate, setAnimate] = useState(false);
  const [reducedMotion, setReducedMotion] = useState(false);
  useEffect(() => {
    try {
      const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
      const apply = () => setReducedMotion(mq.matches);
      apply();
      mq.addEventListener("change", apply);
      return () => mq.removeEventListener("change", apply);
    } catch {}
  }, []);

  const AUTOPLAY_MS = 5000;
  // A reader who asked for reduced motion gets no auto-advance at all — an unprompted
  // 5-second slide is exactly the motion that setting is about.
  const autoplaying = groups.length > 1 && !stopped && !hovering && !reducedMotion;
  useEffect(() => {
    if (!autoplaying) return;
    const t = setTimeout(() => {
      setAnimate(true);
      setSlide((i) => (i + 1) % groups.length);
    }, AUTOPLAY_MS);
    return () => clearTimeout(t);
  }, [autoplaying, slide, groups.length]);

  const goTo = (i) => {
    setStopped(true);
    setAnimate(true);
    setSlide((i + groups.length) % groups.length);
  };

  // Deep link: #community-<config id> selects that config inside its group.
  useEffect(() => {
    const hydrate = () => {
      const hash = (window.location.hash || "").replace(/^#/, "");
      if (!hash.startsWith("community-")) return;
      const id = hash.slice("community-".length);
      for (const [gi, g] of groups.entries()) {
        if ((g.configs || []).some((c) => c.id === id)) {
          // A deep link is an explicit destination; do not slide away from it.
          setStopped(true);
          setSlide(gi);
          setPicked((prev) => ({ ...prev, [groupKey(g)]: id }));
          return;
        }
      }
    };
    hydrate();
    window.addEventListener("hashchange", hydrate);
    return () => window.removeEventListener("hashchange", hydrate);
  }, []);

  const s = makeStyles(isDark);
  const groupKey = (g) => (g.source && g.source.url) || (g.source && g.source.label) || "";

  const copy = (id, text) => {
    // Copying is the strongest signal a reader is using this panel — never slide away.
    setStopped(true);
    try {
      navigator.clipboard.writeText(text);
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 1500);
    } catch {}
  };

  // ==== 4. JSX render ====
  const renderGroup = (g, gi) => {
    const src = g.source || {};
    const configs = g.configs || [];
    if (configs.length === 0) return null;
    const key = groupKey(g) || `group-${gi}`;
    const cfg = configs.find((c) => c.id === picked[key]) || configs[0];
    const mode = runModes[cfg.id] || "python";
    const command = renderCommand(cfg, env, mode);
    const modes = cfg.dockerImage ? ["python", "docker"] : ["python"];
    const gpuCount = gpuCountOf(cfg.flags);
    const knobs = describeFlags(cfg.flags);

    return (
      <div key={key} id={`community-${cfg.id}`} style={{ ...s.group, scrollMarginTop: "104px" }}>
        {/* Credit + the link lead the group — that is what the section is for. */}
        <div style={s.groupHead}>
          <div style={s.who}>
            {src.authorUrl
              ? <a href={src.authorUrl} style={s.prLink} target="_blank" rel="noreferrer">{src.author}</a>
              : src.author}
            {src.org && <span style={s.whoMeta}> · {src.org}</span>}
            {g.reportedAt && <span style={s.whoMeta}> · {g.reportedAt}</span>}
          </div>
          {src.url && (
            <a href={src.url} style={s.prLink} target="_blank" rel="noreferrer">
              {src.label || "source"} ↗
            </a>
          )}
        </div>

        {/* One PR can contribute several configs; chips switch between them. A single
            config needs no chip row — the identity line already names it. */}
        {configs.length > 1 && (
          <div style={s.chipRow}>
            {configs.map((c) => (
              <span
                key={c.id}
                style={s.chip(c.id === cfg.id)}
                role="tab"
                aria-selected={c.id === cfg.id}
                onClick={() => { setStopped(true); setPicked({ ...picked, [key]: c.id }); }}
              >
                {c.title}
              </span>
            ))}
          </div>
        )}

        {/* Identity + knobs, both derived from flags — nothing to keep in sync by hand. */}
        <div style={s.identity}>
          {configs.length === 1 && <span>{cfg.title}</span>}
          {cfg.hardware && <span>· {gpuCount}× {cfg.hardware}</span>}
          {cfg.modelName && <span>· <code>{cfg.modelName}</code></span>}
          {cfg.sglangVersion && <span>· sglang <code>{cfg.sglangVersion}</code></span>}
        </div>
        {knobs.length > 0 && <div style={s.knobs}>{knobs.join(" · ")}</div>}

        <div style={s.commandWrap}>
          <div style={s.commandHeader}>
            <div style={s.runModeWrap} role="tablist" aria-label="Output format">
              {modes.map((m, i) => (
                <span
                  key={m}
                  style={{
                    ...s.runModeChip(mode === m, i === modes.length - 1),
                    ...(modes.length === 1 ? { borderRadius: 7 } : {}),
                  }}
                  role="tab"
                  aria-selected={mode === m}
                  onClick={() => { setStopped(true); setRunModes({ ...runModes, [cfg.id]: m }); }}
                >
                  {m === "docker" ? "Docker" : "Python"}
                </span>
              ))}
            </div>
            <button style={s.iconButton} onClick={() => copy(cfg.id, command)}>
              {copiedId === cfg.id ? "✓ Copied" : "⧉ Copy"}
            </button>
          </div>
          <pre style={s.commandPre}>{command}</pre>
        </div>
      </div>
    );
  };

  return (
    <div
      // NOT "community-configs": Mintlify auto-generates a heading anchor from
      // `## Community Configs`, and a duplicate id would make in-page links resolve to
      // whichever node the browser found first. Same reason _deployment.jsx uses
      // "deployment-configurator" rather than "deployment".
      id="community-config-cards"
      style={{ ...s.container, scrollMarginTop: "104px" }}
      className="not-prose"
    >
      {groups.length === 0 && (
        <div style={s.empty}>
          No community configs for this model yet. Verified one on your hardware? Use the
          Playground's <strong>Submit ↗</strong> button.
        </div>
      )}

      {/* Horizontal carousel: one contribution at a time, so N contributions cost the
          height of one. Every slide stays mounted (translateX, not conditional render)
          so the track's height is stable and a deep-linked anchor is always in the DOM
          for the browser to find. */}
      {groups.length > 0 && (
        <div
          style={s.viewport}
          onMouseEnter={() => setHovering(true)}
          onMouseLeave={() => setHovering(false)}
          // Keyboard focus pauses too, otherwise tabbing into a command's Copy button
          // races the timer.
          onFocus={() => setHovering(true)}
          onBlur={() => setHovering(false)}
          role="group"
          aria-label="Community contributions"
        >
          <div style={s.track(slide, animate && !reducedMotion)}>
            {groups.map((g, gi) => (
              <div
                key={groupKey(g) || `slide-${gi}`}
                style={s.slide}
                aria-hidden={gi !== slide}
              >
                {renderGroup(g, gi)}
              </div>
            ))}
          </div>
        </div>
      )}

      {groups.length > 1 && (
        <div style={s.nav}>
          <button
            type="button" style={s.navBtn} aria-label="Previous contribution"
            onClick={() => goTo(slide - 1)}
          >‹</button>
          {groups.map((g, gi) => (
            <span
              key={`dot-${gi}`}
              style={s.dot(gi === slide)}
              role="button"
              tabIndex={0}
              aria-label={`Contribution ${gi + 1}: ${(g.source && g.source.label) || ""}`}
              aria-current={gi === slide}
              onClick={() => goTo(gi)}
              onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") goTo(gi); }}
            />
          ))}
          <button
            type="button" style={s.navBtn} aria-label="Next contribution"
            onClick={() => goTo(slide + 1)}
          >›</button>
          {/* Says whether it is still advancing, so a stopped carousel does not read as
              broken to someone who expected it to move. */}
          <span style={s.navCount}>
            {slide + 1} / {groups.length}{autoplaying ? "" : " ⏸"}
          </span>
        </div>
      )}

      <div style={s.cta}>
        <span>Ran this model on hardware that isn't in the matrix?</span>
        <button
          type="button"
          onClick={() => {
            const el = document.getElementById("playground");
            if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
          }}
          style={s.ctaButton}
        >
          Submit it from the Playground →
        </button>
      </div>
    </div>
  );
};
