ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG sglang_version=0.4.6.post2+byted.0.0.2.202505261551
ARG sgl_kernel_version=0.1.1+byted.0.0.2.202505261548
ARG gdkv_sdk_version=0.0.1
ARG eic_sdk_version=1.0
ARG absl_version=2.3.0
ARG branch=release_0.0.2

# 编译之前，将源统一设置成内网的
RUN pip config set global.index-url https://bytedpypi.byted.org/simple
RUN sed -i 's/archive.ubuntu.com/mirrors.byted.org/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.byted.org/g' /etc/apt/sources.list

# ep statistics
WORKDIR /sgl-workspace
RUN wget https://github.com/user-attachments/files/20036217/attachment_ep_statistics.zip \
    && unzip attachment_ep_statistics.zip \
    && rm attachment_ep_statistics.zip \
    && mv attachment_ep_statistics /sgl-workspace/eps

# FlashMLA 安装
WORKDIR /sgl-workspace
RUN git clone https://github.com/deepseek-ai/FlashMLA.git
WORKDIR /sgl-workspace/FlashMLA
RUN python3 setup.py install

# sglang 安装
RUN http_proxy='' pip index versions sglang -i https://scqq9isgq31i0fb8nt4eg.apigateway-cn-beijing.volceapi.com/simple/
RUN http_proxy='' pip install "sglang[all]==${sglang_version}" --extra-index-url https://scqq9isgq31i0fb8nt4eg.apigateway-cn-beijing.volceapi.com/simple/ --extra-index-url https://bytedpypi.byted.org/simple

# sgl-kernel安装
RUN http_proxy='' pip install sgl_kernel==${sgl_kernel_version} --extra-index-url https://scqq9isgq31i0fb8nt4eg.apigateway-cn-beijing.volceapi.com/simple/ --extra-index-url https://bytedpypi.byted.org/simple

# gdkv sdk安装
RUN http_proxy='' pip install hpkv==${gdkv_sdk_version} --extra-index-url https://scqq9isgq31i0fb8nt4eg.apigateway-cn-beijing.volceapi.com/simple/ --extra-index-url https://bytedpypi.byted.org/simple

# eic sdk安装
RUN http_proxy='' pip install eic==${eic_sdk_version} --extra-index-url https://scqq9isgq31i0fb8nt4eg.apigateway-cn-beijing.volceapi.com/simple/ --extra-index-url https://bytedpypi.byted.org/simple

# group_gemm依赖安装
RUN http_proxy='' pip install absl-py==${absl_version} --extra-index-url https://bytedpypi.byted.org/simple

# group_gemm 安装
RUN pip install --verbose git+https://github.com/bytedance-iaas/grouped_gemm@dev

# examples 覆盖
RUN cd /tmp && git clone https://github.com/bytedance-iaas/sglang.git -b ${branch} && \
    rm -rf /sgl-workspace/sglang/examples && \
    mkdir -p /sgl-workspace/sglang && \
    cp -r /tmp/sglang/examples /sgl-workspace/sglang/examples && \
    rm -rf /tmp/sglang

# onion 安装
RUN curl -fsSL https://mirrors.byted.org/extra-tools/ubuntu/GPG-KEY-system | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/volc-extra-tools.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/volc-extra-tools.gpg] http://mirrors.byted.org/extra-tools/ubuntu jammy main" > /etc/apt/sources.list.d/volctools.list && \ 
    apt update && apt install -y onion-ai-data

# entrypoint
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]

# 将源统一还原成火山的源
RUN pip config set global.index-url https://mirrors.ivolces.com/pypi/simple/
RUN rm -rf /var/lib/apt/lists/* && \
    sed -i 's/byted.org/ivolces.com/g' /etc/apt/sources.list.d/cuda.list && \
    sed -i 's/byted.org/ivolces.com/g' /etc/apt/sources.list.d/ubuntu.sources && \
    sed -i 's/byted.org/ivolces.com/g' /etc/apt/sources.list.d/volctools.list