ARG BASE_IMAGE=lmsysorg/sglang:v0.5.5-cu129-amd64
ARG UBUNTU_MIRROR=http://mirrors.aliyun.com

FROM ${BASE_IMAGE}

# Replace Ubuntu sources if mirror is specified
RUN if [ -n "$UBUNTU_MIRROR" ]; then \
    sed -i "s|http://.*archive.ubuntu.com|$UBUNTU_MIRROR|g" /etc/apt/sources.list && \
    sed -i "s|http://.*security.ubuntu.com|$UBUNTU_MIRROR|g" /etc/apt/sources.list; \
fi

RUN apt-get update && apt-get install -y --no-install-recommends \
    dnsutils \
  && apt install --only-upgrade -y \
    sudo

RUN python3 -m pip install --no-cache-dir --break-system-packages --no-build-isolation \
    py-spy==0.4.1 \
    vllm==0.11.0 \
    nvtx==0.2.13 \
    -i https://mirrors.aliyun.com/pypi/simple

RUN python3 -m pip install https://git-assert.cnbj1.mi-fds.com/git-assert/mimo/moe_fused_gate-1.0.0-cp312-cp312-linux_x86_64.whl --no-cache-dir  --no-dependencies --force-reinstall
RUN python3 -m pip install https://git-assert.cnbj1.mi-fds.com/git-assert/local_attention_cuda-0.0.0-cp312-cp312-linux_x86_64.whl --no-cache-dir --no-dependencies --force-reinstall
RUN python3 -m pip install nvidia-nccl-cu12==2.28.3 --force-reinstall --no-deps \
    -i https://mirrors.aliyun.com/pypi/simple

COPY . .

# Set workspace directory
WORKDIR /sgl-workspace/sglang
