# default base image
ARG BASE_IMAGE="rocm/vllm-dev:20241022"

FROM $BASE_IMAGE AS base
USER root

WORKDIR /sgl-workspace

ARG SGLANG_REPO="https://github.com/sgl-project/sglang"
ARG SGLANG_BRANCH="v0.3.4.post2"
# RUN python -m pip install orjson python-multipart
# RUN cd /app; git clone ${SGLANG_REPO} \
RUN git clone ${SGLANG_REPO} \
    && cd sglang \
    && git checkout ${SGLANG_BRANCH} \
    && if [ "$BUILD_TYPE" = "srt" ]; then \
         python -m pip --no-cache-dir install -e "python[srt_hip]"; \
       else \
         python -m pip --no-cache-dir install -e "python[all_hip]"; \
       fi

RUN cp -r /sgl-workspace/sglang /sglang
RUN python -m pip cache purge

# Performance environment variable.
ENV MOE_PADDING=1
ENV HIP_FORCE_DEV_KERNARG=1
ENV SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1

CMD ["/bin/bash"]
