ARG BASE_IMAGE=
ARG UBUNTU_MIRROR=http://mirrors.aliyun.com

FROM ${BASE_IMAGE}

# Replace Ubuntu sources if mirror is specified
RUN if [ -n "$UBUNTU_MIRROR" ]; then \
    sed -i "s|http://.*archive.ubuntu.com|$UBUNTU_MIRROR|g" /etc/apt/sources.list && \
    sed -i "s|http://.*security.ubuntu.com|$UBUNTU_MIRROR|g" /etc/apt/sources.list; \
fi

RUN apt-get update && apt-get install -y --no-install-recommends \
    dnsutils \
  && apt install --only-upgrade -y \
    sudo

RUN python3 -m pip install --no-cache-dir --break-system-packages --no-build-isolation \
    py-spy \
    vllm \
    sglang-router \
    -i https://mirrors.aliyun.com/pypi/simple

COPY . .

# Set workspace directory
WORKDIR /sgl-workspace/sglang
