apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: minwm-tianpeng-h100-single-fast
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: minwm-tianpeng-h100-use1
