apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../minwm_quant_round1_b200_spot_20260805.yaml
nameSuffix: -b300-aws03-usw2-v5
patches:
  - path: delete_pvc.yaml
  - path: job_patch.yaml
  - target:
      group: batch
      version: v1
      kind: Job
      name: minwm-quant-r1-b200-20260805-01
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector
        value:
          eks.amazonaws.com/capacityType: SPOT
          eks.amazonaws.com/nodegroup: minwm-spot-p6-b300-0703
          node.kubernetes.io/instance-type: p6-b300.48xlarge
          seedleap.ai/workload: wan22-ti2v
      - op: replace
        path: /spec/template/spec/tolerations
        value:
          - key: seedleap.ai/workload
            operator: Equal
            value: wan22-ti2v
            effect: NoSchedule
