#!/usr/bin/env python3
"""Build the main SGLang wheel from declared source and native inputs."""

from __future__ import annotations

import argparse
import base64
import csv
import hashlib
import io
import re
import tomllib
import zipfile
from pathlib import Path

from packaging.requirements import Requirement
from packaging.version import Version

_SOURCE_PREFIX = "python/"
_PACKAGE_PREFIX = "python/sglang/"
_AOT_PREFIX = "python/sglang/kernels/aot/"


def _mapping(raw: str) -> tuple[str, Path]:
    logical, separator, physical = raw.partition("::=")
    if not separator or not logical or not physical:
        raise ValueError(f"expected LOGICAL::=PHYSICAL mapping, got {raw!r}")
    return logical, Path(physical)


def _is_importable_python(destination: str) -> bool:
    parts = destination.split("/")
    return destination.endswith(".py") and all(
        package.isidentifier() for package in parts[:-1]
    )


def _requirement(raw: str) -> str:
    return str(Requirement(raw))


def _extra_requirement(raw: str, extra: str) -> str:
    requirement = Requirement(raw)
    marker = str(requirement.marker) if requirement.marker else ""
    requirement.marker = None
    suffix = f'extra == "{extra}"'
    if marker:
        suffix = f"({marker}) and {suffix}"
    return f"{requirement}; {suffix}"


def _metadata(pyproject: Path, readme: Path, version: str) -> bytes:
    project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
    headers = [
        "Metadata-Version: 2.4",
        f"Name: {project['name']}",
        f"Version: {version}",
        f"Summary: {project['description']}",
    ]
    headers.extend(
        f"Project-URL: {label}, {url}" for label, url in project.get("urls", {}).items()
    )
    headers.extend(
        f"Classifier: {classifier}" for classifier in project.get("classifiers", [])
    )
    if requires_python := project.get("requires-python"):
        headers.append(f"Requires-Python: {requires_python}")
    headers.append("Description-Content-Type: text/markdown")
    headers.extend(
        f"Requires-Dist: {_requirement(requirement)}"
        for requirement in project.get("dependencies", [])
    )
    for extra, requirements in project.get("optional-dependencies", {}).items():
        headers.append(f"Provides-Extra: {extra}")
        headers.extend(
            f"Requires-Dist: {_extra_requirement(requirement, extra)}"
            for requirement in requirements
        )
    description = readme.read_text(encoding="utf-8")
    return ("\n".join(headers) + "\n\n" + description).encode()


def _version_tuple(version: Version) -> tuple[int | str, ...]:
    parts: list[int | str] = list(version.release)
    if version.pre:
        parts.append(f"{version.pre[0]}{version.pre[1]}")
    if version.post is not None:
        parts.append(f"post{version.post}")
    if version.dev is not None:
        parts.append(f"dev{version.dev}")
    if version.local:
        parts.extend(
            int(part) if part.isdigit() else part
            for part in re.split(r"[.-]", version.local)
        )
    return tuple(parts)


def _version_module(version: str) -> bytes:
    parsed = Version(version)
    return f"""\
# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = {str(parsed)!r}
__version_tuple__ = version_tuple = {_version_tuple(parsed)!r}

__commit_id__ = commit_id = None
""".encode()


def _wheel_metadata(tag: str) -> bytes:
    return f"""\
Wheel-Version: 1.0
Generator: sglang-bazel
Root-Is-Purelib: false
Tag: {tag}

""".encode()


def _entry_points(pyproject: Path) -> bytes:
    scripts = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"].get(
        "scripts", {}
    )
    lines = ["[console_scripts]"]
    lines.extend(f"{name} = {target}" for name, target in sorted(scripts.items()))
    return ("\n".join(lines) + "\n").encode()


def _zip_info(
    name: str, *, executable: bool = False, mode: int | None = None
) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
    info.compress_type = zipfile.ZIP_DEFLATED
    info.create_system = 3
    permissions = mode if mode is not None else (0o755 if executable else 0o644)
    info.external_attr = (0o100000 | permissions) << 16
    return info


def _record(payload: dict[str, tuple[bytes, bool]], record_path: str) -> bytes:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    for name in sorted(payload):
        contents = payload[name][0]
        digest = base64.urlsafe_b64encode(hashlib.sha256(contents).digest()).rstrip(
            b"="
        )
        writer.writerow((name, f"sha256={digest.decode()}", len(contents)))
    writer.writerow((record_path, "", ""))
    return output.getvalue().encode()


def _payload(args: argparse.Namespace) -> tuple[dict[str, tuple[bytes, bool]], str]:
    version = str(Version(args.version))
    if args.version != version:
        raise ValueError(
            f"version must already be PEP 440 canonical: {args.version!r} != {version!r}"
        )
    distribution = tomllib.loads(args.pyproject.read_text(encoding="utf-8"))["project"][
        "name"
    ]
    if args.distribution != distribution:
        raise ValueError(
            "declared distribution does not match pyproject: "
            f"{args.distribution!r} != {distribution!r}"
        )
    dist_info = f"{distribution.replace('-', '_')}-{version}.dist-info"
    payload: dict[str, tuple[bytes, bool]] = {}

    for raw_mapping in args.source:
        logical, physical = _mapping(raw_mapping)
        if not logical.startswith(_PACKAGE_PREFIX) or logical.startswith(_AOT_PREFIX):
            continue
        destination = logical.removeprefix(_SOURCE_PREFIX)
        if destination in payload:
            raise ValueError(f"duplicate wheel destination {destination!r}")
        executable = bool(
            physical.stat().st_mode & 0o111
        ) and not _is_importable_python(destination)
        payload[destination] = (physical.read_bytes(), executable)

    payload["sglang/_version.py"] = (_version_module(version), False)
    for raw_mapping in args.native_extension:
        module, physical = _mapping(raw_mapping)
        if not module.startswith("sglang."):
            raise ValueError(f"native module must be below sglang: {module!r}")
        destination = module.replace(".", "/") + args.extension_suffix
        if destination in payload:
            raise ValueError(f"duplicate wheel destination {destination!r}")
        payload[destination] = (physical.read_bytes(), True)

    payload[f"{dist_info}/METADATA"] = (
        _metadata(args.pyproject, args.readme, version),
        False,
    )
    payload[f"{dist_info}/WHEEL"] = (_wheel_metadata(args.tag), False)
    payload[f"{dist_info}/entry_points.txt"] = (_entry_points(args.pyproject), False)
    payload[f"{dist_info}/top_level.txt"] = (b"sglang\n", False)
    return payload, dist_info


def main() -> None:
    parser = argparse.ArgumentParser(fromfile_prefix_chars="@")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--distribution", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--tag", required=True)
    parser.add_argument("--extension-suffix", required=True)
    parser.add_argument("--pyproject", type=Path, required=True)
    parser.add_argument("--readme", type=Path, required=True)
    parser.add_argument("--source", action="append", default=[])
    parser.add_argument("--native-extension", action="append", default=[])
    args = parser.parse_args()

    payload, dist_info = _payload(args)
    record_path = f"{dist_info}/RECORD"
    record = _record(payload, record_path)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(
        args.output,
        "w",
        compression=zipfile.ZIP_DEFLATED,
        compresslevel=9,
        strict_timestamps=True,
    ) as archive:
        for name in sorted(payload):
            contents, executable = payload[name]
            archive.writestr(_zip_info(name, executable=executable), contents)
        archive.writestr(_zip_info(record_path, mode=0o664), record)


if __name__ == "__main__":
    main()
