load(":toolchain.bzl", "kernel_cuda_toolchain")

package(default_visibility = ["//visibility:public"])

toolchain_type(name = "kernel_toolchain_type")

kernel_cuda_toolchain(
    name = "cuda_13_0_torch_2_13_cp312_abi1",
    build_python_packages = [
        "@cuda_packaging//:files",
        "@cuda_pathspec//:files",
        "@cuda_scikit_build_core//:files",
        "@cuda_wheel//:files",
    ],
    cuda_architectures = [
        "80",
        "86",
        "89",
        "90",
        "90a",
        "100f",
        "120a",
    ],
    cuda_files = "@cuda_13_0_linux_x86_64//:files",
    cuda_version = "13.0",
    python_abi = "cp312",
    torch_cxx11_abi = 1,
    torch_files = "@cuda_torch_2_13_cp312_linux_x86_64//:files",
    torch_version = "2.13.0+cu130",
)

toolchain(
    name = "cuda_13_0_torch_2_13_cp312_abi1_toolchain",
    exec_compatible_with = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
    target_compatible_with = ["//bazel/platforms:cuda"],
    toolchain = ":cuda_13_0_torch_2_13_cp312_abi1",
    toolchain_type = ":kernel_toolchain_type",
)
