import argparse
import json
import logging
import os
import signal
import sys
import time
from typing import Any

from memcache_hybrid import DistributedObjectStore, LocalConfig

logger = logging.getLogger("ascend_memcache.start_local_store")

# Keys consumed by this launcher, not forwarded to LocalConfig.
_CTRL_KEYS = frozenset({"device_id", "init_bm", "conf_file_path"})
_CONF_KEY_MAP = {
    "meta_service_url": "ock.mmc.meta_service_url",
    "config_store_url": "ock.mmc.local_service.config_store_url",
    "log_level": "ock.mmc.log_level",
    "world_size": "ock.mmc.local_service.world_size",
    "protocol": "ock.mmc.local_service.protocol",
    "hcom_url": "ock.mmc.local_service.hcom_url",
    "dram_size": "ock.mmc.local_service.dram.size",
    "hbm_size": "ock.mmc.local_service.hbm.size",
    "max_dram_size": "ock.mmc.local_service.max.dram.size",
    "max_hbm_size": "ock.mmc.local_service.max.hbm.size",
}
_CONF_CTRL_KEYS = frozenset(
    set(_CTRL_KEYS)
    | {
        "metrics_url",
        "memcache_metrics_url",
        "check_server",
        "extra_backend_tag",
    }
)


def _load_json_config(config_path: str) -> dict[str, Any]:
    with open(config_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Config file must contain a JSON object: {config_path}")
    return data


def _apply_local_config(config: LocalConfig, data: dict[str, Any]) -> list[str]:
    unknown: list[str] = []
    for key, value in data.items():
        if key in _CTRL_KEYS:
            continue
        if key in _CONF_KEY_MAP or key.startswith("ock.mmc."):
            continue
        if hasattr(config, key):
            setattr(config, key, value)
        else:
            unknown.append(key)
    return unknown


def _format_conf_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _build_local_conf_entries(data: dict[str, Any]) -> dict[str, str]:
    entries: dict[str, str] = {}
    for key, value in data.items():
        if key in _CONF_CTRL_KEYS:
            continue
        if value is None:
            continue
        if key.startswith("ock.mmc."):
            entries[key] = _format_conf_value(value)
            continue
        mapped = _CONF_KEY_MAP.get(key)
        if mapped is not None:
            entries[mapped] = _format_conf_value(value)
    return entries


def _write_local_conf(conf_file_path: str, data: dict[str, Any]) -> None:
    entries = _build_local_conf_entries(data)
    if not entries:
        logger.info(
            "No conf-compatible keys found in JSON; keep existing local conf unchanged: %s",
            conf_file_path,
        )
        return

    parent = os.path.dirname(os.path.abspath(conf_file_path))
    if parent:
        os.makedirs(parent, exist_ok=True)

    lines = [
        "# Auto-generated by start_local_store.py from JSON config.",
        "# You can override any key by editing localservice_config.json.",
        "",
    ]
    for key in sorted(entries):
        lines.append(f"{key} = {entries[key]}")
    lines.append("")

    with open(conf_file_path, "w", encoding="utf-8") as fout:
        fout.write("\n".join(lines))

    logger.info(
        "Wrote %d LocalService conf entries to %s", len(entries), conf_file_path
    )


def launch_local_store(config_path: str, block: bool = True) -> int:
    try:
        config_data = _load_json_config(config_path)
    except Exception as e:
        logger.error("Failed to load local store config from %s: %s", config_path, e)
        return 1

    local_cfg = LocalConfig()
    unknown = _apply_local_config(local_cfg, config_data)
    if unknown:
        logger.warning("Ignoring unknown LocalConfig keys: %s", unknown)

    for attr in [
        "meta_service_url",
        "config_store_url",
        "log_level",
        "world_size",
        "protocol",
        "hcom_url",
        "dram_size",
        "hbm_size",
        "max_dram_size",
        "max_hbm_size",
    ]:
        if attr in config_data and hasattr(local_cfg, attr):
            setattr(local_cfg, attr, config_data[attr])

    if hasattr(local_cfg, "protocol"):
        local_cfg.protocol = config_data.get("protocol", "host_tcp")

    logger.info(
        "Resolved LocalConfig: protocol=%s, config_store_url=%s, dram_size=%s, hbm_size=%s",
        getattr(local_cfg, "protocol", None),
        getattr(local_cfg, "config_store_url", None),
        getattr(local_cfg, "dram_size", None),
        getattr(local_cfg, "hbm_size", None),
    )

    device_id = int(config_data.get("device_id", 0))
    init_bm = bool(config_data.get("init_bm", True))
    conf_file_path = config_data.get("conf_file_path")
    if conf_file_path:
        conf_file_path = str(conf_file_path).strip()
        if conf_file_path:
            _write_local_conf(conf_file_path, config_data)
            # Keep compatibility with memcache_hybrid "env + conf file" startup mode.
            os.environ["MMC_LOCAL_CONFIG_PATH"] = conf_file_path
            logger.info(
                "Set MMC_LOCAL_CONFIG_PATH from config file: %s", conf_file_path
            )

    store = DistributedObjectStore()
    ret = store.setup(local_cfg)
    if ret != 0:
        logger.error("DistributedObjectStore.setup failed, ret=%s", ret)
        return ret if isinstance(ret, int) else 2

    ret = store.init(device_id, init_bm)
    if ret != 0:
        logger.error(
            "DistributedObjectStore.init failed, device_id=%s init_bm=%s ret=%s",
            device_id,
            init_bm,
            ret,
        )
        return ret if isinstance(ret, int) else 3

    logger.info(
        "Local store started successfully: config=%s device_id=%s init_bm=%s",
        config_path,
        device_id,
        init_bm,
    )

    if not block:
        return 0

    stop = {"value": False}

    def _handle_sig(_signum, _frame):
        stop["value"] = True

    signal.signal(signal.SIGINT, _handle_sig)
    signal.signal(signal.SIGTERM, _handle_sig)

    logger.info("Local store is running. Press Ctrl+C to stop.")
    try:
        while not stop["value"]:
            time.sleep(1)
    finally:
        try:
            store.close()
        except Exception as e:
            logger.warning("DistributedObjectStore.close failed: %s", e)
    logger.info("Local store stopped.")
    return 0


def main() -> int:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_path = os.path.join(script_dir, "localservice_config.json")

    parser = argparse.ArgumentParser(
        description="Launch Ascend MemCache local DistributedObjectStore via JSON."
    )
    parser.add_argument(
        "--config_path",
        type=str,
        default=default_path,
        help=f"Path to local config JSON (default: {default_path})",
    )
    parser.add_argument(
        "--no-block",
        action="store_true",
        help="Initialize store and exit without keeping process alive.",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    return launch_local_store(args.config_path, block=not args.no_block)


if __name__ == "__main__":
    sys.exit(main())