# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: load_report.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'load_report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11load_report.proto\x12\nkv_load.v1\"\xab\x04\n\nLoadSample\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\x12\x0f\n\x07\x64p_rank\x18\x03 \x01(\r\x12\x14\n\x0cworker_epoch\x18\x04 \x01(\t\x12\x1a\n\x12registration_token\x18\x05 \x01(\t\x12\x10\n\x08sequence\x18\x06 \x01(\x04\x12\x18\n\x10num_running_reqs\x18\x07 \x01(\x04\x12\x18\n\x10num_waiting_reqs\x18\x08 \x01(\x04\x12\x17\n\x0fnum_used_tokens\x18\t \x01(\x04\x12\x1c\n\x14max_total_num_tokens\x18\n \x01(\x04\x12#\n\x1bnum_waiting_uncached_tokens\x18\x0b \x01(\x04\x12\x18\n\x10num_total_tokens\x18\x0c \x01(\x04\x12\x1c\n\x14max_running_requests\x18\r \x01(\x04\x12%\n\x1dtotal_prefill_uncached_tokens\x18\x0e \x01(\x04\x12\x1d\n\x15total_prefill_busy_us\x18\x0f \x01(\x04\x12\x1d\n\x15generation_throughput\x18\x10 \x01(\x01\x12\x16\n\x0e\x63\x61\x63he_hit_rate\x18\x11 \x01(\x01\x12\x13\n\x0butilization\x18\x12 \x01(\x01\x12\x18\n\x10num_prefill_reqs\x18\x13 \x01(\x04\x12\x17\n\x0fnum_decode_reqs\x18\x14 \x01(\x04\x12\x15\n\rsample_age_ms\x18\x15 \x01(\x04\"\x0f\n\rLoadReportAck2L\n\x0bLoadMonitor\x12=\n\x06Report\x12\x16.kv_load.v1.LoadSample\x1a\x19.kv_load.v1.LoadReportAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'load_report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADSAMPLE']._serialized_start=34
  _globals['_LOADSAMPLE']._serialized_end=589
  _globals['_LOADREPORTACK']._serialized_start=591
  _globals['_LOADREPORTACK']._serialized_end=606
  _globals['_LOADMONITOR']._serialized_start=608
  _globals['_LOADMONITOR']._serialized_end=684
# @@protoc_insertion_point(module_scope)
