apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cpu-control-plane.yaml
  - west-s3-volume.yaml
  - observability.yaml
  - coordinator.yaml
  - gateway.yaml
  - worker-discovery.yaml
  - network-policy.yaml
  - autoscaling.yaml
  - gpu-scheduled-scaling.yaml
  - h100-denoiser.yaml
  - l4-vae.yaml
  - gateway-service.yaml
