load("//bazel/packaging:source_glob.bzl", "pep517_source_glob")

package(default_visibility = ["//visibility:public"])

exports_files([
    "pyproject.toml",
    "pyproject_cpu.toml",
    "pyproject_npu.toml",
    "pyproject_other.toml",
    "pyproject_xpu.toml",
    "setup.py",
])

filegroup(
    name = "main_wheel_pep517_sources",
    srcs = pep517_source_glob(["*"]) + ["//python/sglang:main_wheel_pep517_sources"],
)
