"""
Unit tests for structural tag format generation.

Tests that structural tags are correctly generated by each detector,
including schema inclusion, parameter handling, and format structure.
"""

import unittest
from typing import Dict, List

from sglang.srt.entrypoints.openai.protocol import Tool
from sglang.srt.function_call.deepseekv3_detector import DeepSeekV3Detector
from sglang.srt.function_call.deepseekv31_detector import DeepSeekV31Detector
from sglang.srt.function_call.gpt_oss_detector import GptOssDetector
from sglang.srt.function_call.kimik2_detector import KimiK2Detector
from sglang.srt.function_call.llama32_detector import Llama32Detector
from sglang.srt.function_call.mistral_detector import MistralDetector
from sglang.srt.function_call.qwen25_detector import Qwen25Detector
from sglang.srt.function_call.qwen3_coder_detector import Qwen3CoderDetector


class StructuralTagFormatTestCase(unittest.TestCase):
    """Base test case for structural tag format tests."""

    def get_simple_tool(self) -> Tool:
        """Get a simple tool with basic parameters."""
        return Tool(
            type="function",
            function={
                "name": "get_weather",
                "description": "Get weather information",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "city": {"type": "string", "description": "City name"},
                        "unit": {
                            "type": "string",
                            "enum": ["celsius", "fahrenheit"],
                        },
                    },
                    "required": ["city"],
                },
            },
        )

    def get_empty_params_tool(self) -> Tool:
        """Get a tool with no parameters."""
        return Tool(
            type="function",
            function={
                "name": "get_time",
                "description": "Get current time",
                "parameters": None,
            },
        )

    def get_complex_tool(self) -> Tool:
        """Get a tool with complex nested parameters."""
        return Tool(
            type="function",
            function={
                "name": "analyze_data",
                "description": "Analyze complex data",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "object",
                            "properties": {
                                "metrics": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                },
                                "config": {
                                    "type": "object",
                                    "properties": {
                                        "threshold": {"type": "number"},
                                        "enabled": {"type": "boolean"},
                                    },
                                },
                            },
                            "required": ["metrics"],
                        },
                    },
                    "required": ["data"],
                },
            },
        )

    def assert_structural_tag_structure(self, tag: Dict, expected_tools_count: int):
        """Assert that structural tag has correct structure."""
        self.assertIn("format", tag)
        self.assertIn("type", tag["format"])
        self.assertEqual(tag["format"]["type"], "triggered_tags")
        self.assertIn("triggers", tag["format"])
        self.assertIn("tags", tag["format"])
        self.assertIsInstance(tag["format"]["tags"], list)
        self.assertEqual(len(tag["format"]["tags"]), expected_tools_count)

    def assert_schema_always_included(self, tag: Dict):
        """Assert that json_schema is always included in tag content."""
        for tag_item in tag["format"]["tags"]:
            self.assertIn("content", tag_item)
            self.assertIn("type", tag_item["content"])
            content_type = tag_item["content"]["type"]
            
            # Handle different content types:
            # - Most detectors use "json_schema"
            # - DeepSeekV3 uses nested "tags_with_separator" (check inner tags)
            # - Qwen3Coder uses "qwen_xml_parameter"
            if content_type == "tags_with_separator":
                # DeepSeekV3 nested structure - check inner tags
                self.assertIn("tags", tag_item["content"])
                for inner_tag in tag_item["content"]["tags"]:
                    self.assertIn("content", inner_tag)
                    self.assertIn("type", inner_tag["content"])
                    self.assertEqual(inner_tag["content"]["type"], "json_schema")
                    self.assertIn("json_schema", inner_tag["content"])
            elif content_type == "qwen_xml_parameter":
                # Qwen3Coder uses qwen_xml_parameter but still has json_schema
                self.assertIn("json_schema", tag_item["content"])
            else:
                # Standard json_schema format
                self.assertEqual(content_type, "json_schema")
                self.assertIn("json_schema", tag_item["content"])


class TestLlama32Detector(StructuralTagFormatTestCase):
    """Test structural tag generation for Llama32Detector."""

    def setUp(self):
        self.detector = Llama32Detector()

    def test_schema_always_included(self):
        """Test that schema is always included even with at_least_one=False."""
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_schema_always_included(tag)

    def test_at_least_one_parameter(self):
        """Test that at_least_one parameter affects structural tag format."""
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        self.assertFalse(tag_false["format"]["at_least_one"])
        self.assertTrue(tag_true["format"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        """Test that stop_after_first parameter affects structural tag format."""
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(tag_false["format"]["stop_after_first"])
        self.assertTrue(tag_true["format"]["stop_after_first"])

    def test_multiple_tools(self):
        """Test that multiple tools generate multiple tags."""
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=2)
        self.assert_schema_always_included(tag)

    def test_empty_parameters_handling(self):
        """Test handling of tools with no parameters."""
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=1)
        self.assert_schema_always_included(tag)
        # Empty parameters should result in empty dict schema
        schema = tag["format"]["tags"][0]["content"]["json_schema"]
        self.assertEqual(schema, {})


class TestMistralDetector(StructuralTagFormatTestCase):
    """Test structural tag generation for MistralDetector."""

    def setUp(self):
        self.detector = MistralDetector()

    def test_schema_always_included(self):
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_schema_always_included(tag)

    def test_at_least_one_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        self.assertFalse(tag_false["format"]["at_least_one"])
        self.assertTrue(tag_true["format"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(tag_false["format"]["stop_after_first"])
        self.assertTrue(tag_true["format"]["stop_after_first"])

    def test_multiple_tools(self):
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=2)

    def test_empty_parameters_handling(self):
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=1)
        schema = tag["format"]["tags"][0]["content"]["json_schema"]
        self.assertEqual(schema, {})


class TestQwen25Detector(StructuralTagFormatTestCase):
    """Test structural tag generation for Qwen25Detector."""

    def setUp(self):
        self.detector = Qwen25Detector()

    def test_schema_always_included(self):
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_schema_always_included(tag)

    def test_at_least_one_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        self.assertFalse(tag_false["format"]["at_least_one"])
        self.assertTrue(tag_true["format"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(tag_false["format"]["stop_after_first"])
        self.assertTrue(tag_true["format"]["stop_after_first"])

    def test_multiple_tools(self):
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=2)

    def test_empty_parameters_handling(self):
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=1)
        schema = tag["format"]["tags"][0]["content"]["json_schema"]
        self.assertEqual(schema, {})


class TestQwen3CoderDetector(StructuralTagFormatTestCase):
    """Test structural tag generation for Qwen3CoderDetector."""

    def setUp(self):
        self.detector = Qwen3CoderDetector()

    def test_schema_always_included(self):
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_schema_always_included(tag)

    def test_at_least_one_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        self.assertFalse(tag_false["format"]["at_least_one"])
        self.assertTrue(tag_true["format"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(tag_false["format"]["stop_after_first"])
        self.assertTrue(tag_true["format"]["stop_after_first"])

    def test_multiple_tools(self):
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=2)

    def test_empty_parameters_handling(self):
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=1)
        schema = tag["format"]["tags"][0]["content"]["json_schema"]
        self.assertEqual(schema, {})


class TestDeepSeekV3Detector(StructuralTagFormatTestCase):
    """Test structural tag generation for DeepSeekV3Detector."""

    def setUp(self):
        self.detector = DeepSeekV3Detector()

    def test_schema_always_included(self):
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_schema_always_included(tag)

    def test_at_least_one_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        # DeepSeekV3 uses nested structure, check inner tag
        inner_false = tag_false["format"]["tags"][0]["content"]["tags"][0]
        inner_true = tag_true["format"]["tags"][0]["content"]["tags"][0]
        # The at_least_one is in the inner tags_with_separator
        # Actually, let's check the structure - it's nested
        self.assertIn("at_least_one", tag_false["format"]["tags"][0]["content"])
        self.assertFalse(tag_false["format"]["tags"][0]["content"]["at_least_one"])
        self.assertTrue(tag_true["format"]["tags"][0]["content"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(
            tag_false["format"]["tags"][0]["content"]["stop_after_first"]
        )
        self.assertTrue(tag_true["format"]["tags"][0]["content"]["stop_after_first"])

    def test_multiple_tools(self):
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        # DeepSeekV3 wraps all tools in a single outer tag
        self.assertIn("format", tag)
        # Check that inner tags contain both tools
        inner_tags = tag["format"]["tags"][0]["content"]["tags"]
        self.assertEqual(len(inner_tags), 2)

    def test_empty_parameters_handling(self):
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assertIn("format", tag)
        # DeepSeekV3 has nested structure
        inner_tag = tag["format"]["tags"][0]["content"]["tags"][0]
        schema = inner_tag["content"]["json_schema"]
        self.assertEqual(schema, {})


class TestDeepSeekV31Detector(StructuralTagFormatTestCase):
    """Test structural tag generation for DeepSeekV31Detector."""

    def setUp(self):
        self.detector = DeepSeekV31Detector()

    def test_schema_always_included(self):
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        # DeepSeekV31 has nested structure
        inner_tag = tag["format"]["tags"][0]["content"]["tags"][0]
        self.assertIn("content", inner_tag)
        self.assertIn("json_schema", inner_tag["content"])

    def test_at_least_one_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        self.assertFalse(
            tag_false["format"]["tags"][0]["content"]["at_least_one"]
        )
        self.assertTrue(tag_true["format"]["tags"][0]["content"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(
            tag_false["format"]["tags"][0]["content"]["stop_after_first"]
        )
        self.assertTrue(tag_true["format"]["tags"][0]["content"]["stop_after_first"])

    def test_multiple_tools(self):
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        inner_tags = tag["format"]["tags"][0]["content"]["tags"]
        self.assertEqual(len(inner_tags), 2)

    def test_empty_parameters_handling(self):
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        inner_tag = tag["format"]["tags"][0]["content"]["tags"][0]
        schema = inner_tag["content"]["json_schema"]
        self.assertEqual(schema, {})


class TestGptOssDetector(StructuralTagFormatTestCase):
    """Test structural tag generation for GptOssDetector."""

    def setUp(self):
        self.detector = GptOssDetector()

    def test_schema_always_included(self):
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        # GPT-OSS has two patterns per tool (reasoning enabled/disabled)
        self.assertEqual(len(tag["format"]["tags"]), 2)
        for tag_item in tag["format"]["tags"]:
            self.assertIn("content", tag_item)
            self.assertIn("json_schema", tag_item["content"])

    def test_at_least_one_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        self.assertFalse(tag_false["format"]["at_least_one"])
        self.assertTrue(tag_true["format"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(tag_false["format"]["stop_after_first"])
        self.assertTrue(tag_true["format"]["stop_after_first"])

    def test_multiple_tools(self):
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        # GPT-OSS has 2 patterns per tool
        self.assertEqual(len(tag["format"]["tags"]), 4)

    def test_empty_parameters_handling(self):
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assertEqual(len(tag["format"]["tags"]), 2)
        for tag_item in tag["format"]["tags"]:
            schema = tag_item["content"]["json_schema"]
            self.assertEqual(schema, {})


class TestKimiK2Detector(StructuralTagFormatTestCase):
    """Test structural tag generation for KimiK2Detector."""

    def setUp(self):
        self.detector = KimiK2Detector()

    def test_schema_always_included(self):
        tool = self.get_simple_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_schema_always_included(tag)

    def test_at_least_one_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=True, stop_after_first=False
        )
        self.assertFalse(tag_false["format"]["at_least_one"])
        self.assertTrue(tag_true["format"]["at_least_one"])

    def test_stop_after_first_parameter(self):
        tool = self.get_simple_tool()
        tag_false = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        tag_true = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=True
        )
        self.assertFalse(tag_false["format"]["stop_after_first"])
        self.assertTrue(tag_true["format"]["stop_after_first"])

    def test_multiple_tools(self):
        tools = [self.get_simple_tool(), self.get_complex_tool()]
        tag = self.detector.build_structural_tag(
            tools=tools, at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=2)

    def test_empty_parameters_handling(self):
        tool = self.get_empty_params_tool()
        tag = self.detector.build_structural_tag(
            tools=[tool], at_least_one=False, stop_after_first=False
        )
        self.assert_structural_tag_structure(tag, expected_tools_count=1)
        schema = tag["format"]["tags"][0]["content"]["json_schema"]
        self.assertEqual(schema, {})


# Note: Glm4MoeDetector, PythonicDetector, Step3Detector, and MinimaxM2Detector
# return False for supports_structural_tag() and raise NotImplementedError
# for build_structural_tag(), so they are not tested here.


if __name__ == "__main__":
    unittest.main()

