# SPDX-License-Identifier: Apache-2.0

"""External SenseNova U1 e2e precision check.

These tests require a running omni server. The precision test also requires a
reference image generated by the official/native pipeline. They exercise the
public HTTP path so regressions across the SRT engine, omni coordinator, and
multimodal_gen image generation path are caught together.
"""

import base64
import json
import math
import os
import unittest
from io import BytesIO
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

import numpy as np
from PIL import Image, ImageFilter

T2I_REFERENCE_ENV = "SGLANG_OMNI_U1_T2I_REFERENCE_IMAGE"
EDIT_INPUT_ENV = "SGLANG_OMNI_U1_EDIT_INPUT_IMAGE"
EDIT_REFERENCE_ENV = "SGLANG_OMNI_U1_EDIT_REFERENCE_IMAGE"
THREE_TURN_REFERENCE_ENV = "SGLANG_OMNI_U1_THREE_TURN_REFERENCE_IMAGE"
THREE_TURN_OUTPUT_ENV = "SGLANG_OMNI_U1_THREE_TURN_OUTPUT_IMAGE"
REFERENCE_DIR = Path(__file__).with_name("references") / "sensenova_u1"
T2I_REFERENCE_PATH = REFERENCE_DIR / "t2i_512_1step.png"
EDIT_REFERENCE_PATH = REFERENCE_DIR / "edit_512_1step.png"
THREE_TURN_REFERENCE_PATH = REFERENCE_DIR / "three_turn_1024_seed7.png"
THREE_TURN_PROMPTS = (
    (
        "Create one clean studio image of a matte cobalt-blue cube centered on a "
        "white tabletop, with a plain light-gray background. After the image, "
        "describe the cube color and table in one short sentence."
    ),
    (
        "Continue from the previous generated image. Edit it so the cube becomes "
        "bright red and add one glossy green sphere on its right. Keep the same "
        "tabletop, camera angle, and background, then explain exactly what changed."
    ),
    "Continue from the previous generated image. Edit it so the cube becomes a capybara",
)
T2I_PRECISION_PROMPT = (
    "Create one clean studio image of a matte cobalt-blue cube centered on a "
    "white tabletop, plain light-gray background."
)
EDIT_PRECISION_PROMPT = (
    "Edit the image so the cube becomes bright red and add one glossy green "
    "sphere on its right. Keep the same tabletop, camera angle, and background."
)


class TestSenseNovaU1E2EPrecision(unittest.TestCase):
    def test_t2i_matches_reference_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        response = _run_turn(
            base_url,
            model=model,
            task="t2i",
            text=T2I_PRECISION_PROMPT,
            sampling_params=_precision_sampling_params(
                "SGLANG_OMNI_U1_T2I",
                default_width=512,
                default_height=512,
                default_num_steps=1,
                default_cfg_text_scale=1.0,
                default_cfg_img_scale=1.0,
            ),
            max_images=1,
        )

        _assert_reference_match(
            response,
            reference_env=T2I_REFERENCE_ENV,
            default_reference_path=T2I_REFERENCE_PATH,
            output_env="SGLANG_OMNI_U1_T2I_OUTPUT_IMAGE",
            metric_prefix="SGLANG_OMNI_U1_T2I",
        )

    def test_edit_matches_reference_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        response = _run_turn(
            base_url,
            model=model,
            task="edit",
            text=EDIT_PRECISION_PROMPT,
            messages=[
                _image_segment_from_path(
                    _path_from_env(EDIT_INPUT_ENV, T2I_REFERENCE_PATH)
                ),
                {"type": "text", "text": EDIT_PRECISION_PROMPT},
            ],
            sampling_params=_precision_sampling_params(
                "SGLANG_OMNI_U1_EDIT",
                default_width=512,
                default_height=512,
                default_num_steps=1,
                default_cfg_text_scale=1.0,
                default_cfg_img_scale=1.0,
            ),
            max_images=1,
        )

        _assert_reference_match(
            response,
            reference_env=EDIT_REFERENCE_ENV,
            default_reference_path=EDIT_REFERENCE_PATH,
            output_env="SGLANG_OMNI_U1_EDIT_OUTPUT_IMAGE",
            metric_prefix="SGLANG_OMNI_U1_EDIT",
        )

    def test_three_turn_interleave_edit_matches_reference_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        sampling_params = {
            "width": _env_int("SGLANG_OMNI_U1_WIDTH", 1024),
            "height": _env_int("SGLANG_OMNI_U1_HEIGHT", 1024),
            "num_steps": _env_int("SGLANG_OMNI_U1_STEPS", 50),
            "seed": _env_int("SGLANG_OMNI_U1_SEED", 7),
            "cfg_text_scale": _env_float("SGLANG_OMNI_U1_CFG_TEXT_SCALE", 4.0),
            "cfg_img_scale": _env_float("SGLANG_OMNI_U1_CFG_IMG_SCALE", 1.0),
            "cfg_interval": [
                _env_float("SGLANG_OMNI_U1_CFG_START", 0.0),
                _env_float("SGLANG_OMNI_U1_CFG_END", 1.0),
            ],
            "cfg_renorm_type": os.getenv("SGLANG_OMNI_U1_CFG_RENORM_TYPE", "none"),
            "t_eps": _env_float("SGLANG_OMNI_U1_T_EPS", 0.02),
        }
        session_id = None
        try:
            first = _run_turn(
                base_url,
                model=model,
                text=THREE_TURN_PROMPTS[0],
                sampling_params=sampling_params,
                keep_session=True,
            )
            session_id = first["session"]["id"]
            _save_output_image(first, "SGLANG_OMNI_U1_TURN1_OUTPUT_IMAGE")
            self.assertIsNotNone(_last_image(first))

            second = _run_turn(
                base_url,
                model=model,
                text=THREE_TURN_PROMPTS[1],
                sampling_params=sampling_params,
                session_id=session_id,
            )
            _save_output_image(second, "SGLANG_OMNI_U1_TURN2_OUTPUT_IMAGE")
            self.assertIsNotNone(_last_image(second))

            third = _run_turn(
                base_url,
                model=model,
                text=THREE_TURN_PROMPTS[2],
                sampling_params=sampling_params,
                session_id=session_id,
            )
            actual = _last_image(third)
            reference = Image.open(
                _path_from_env(THREE_TURN_REFERENCE_ENV, THREE_TURN_REFERENCE_PATH)
            ).convert("RGB")
            metrics = _compare_images(actual, reference)

            output_path = os.getenv(THREE_TURN_OUTPUT_ENV)
            if output_path:
                actual.save(output_path)
            _save_output_image(third, "SGLANG_OMNI_U1_TURN3_OUTPUT_IMAGE")

            self.assertGreaterEqual(
                metrics["psnr"],
                _env_float("SGLANG_OMNI_U1_MIN_PSNR", 45.0),
                metrics,
            )
            self.assertLessEqual(
                metrics["mae"],
                _env_float("SGLANG_OMNI_U1_MAX_MAE", 1.5),
                metrics,
            )
            self.assertGreaterEqual(
                metrics["cosine"],
                _env_float("SGLANG_OMNI_U1_MIN_COSINE", 0.999),
                metrics,
            )
        finally:
            if session_id is not None:
                _post_json(
                    base_url,
                    "/v1/omni/generate",
                    {"action": "close_session", "session_id": session_id},
                    raise_on_error=False,
                )


class TestSenseNovaU1E2EBehavior(unittest.TestCase):
    def test_interleave_hi_think_false_generates_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        sampling_params = {
            "width": _env_int("SGLANG_OMNI_U1_HI_WIDTH", 512),
            "height": _env_int("SGLANG_OMNI_U1_HI_HEIGHT", 512),
            "num_steps": _env_int("SGLANG_OMNI_U1_HI_STEPS", 4),
            "seed": _env_int("SGLANG_OMNI_U1_HI_SEED", 223),
            "cfg_text_scale": _env_float("SGLANG_OMNI_U1_HI_CFG_TEXT_SCALE", 1.0),
            "cfg_img_scale": _env_float("SGLANG_OMNI_U1_HI_CFG_IMG_SCALE", 1.0),
            "cfg_interval": [0.0, 1.0],
            "cfg_renorm_type": "none",
            "t_eps": _env_float("SGLANG_OMNI_U1_HI_T_EPS", 0.02),
        }

        response = _run_turn(
            base_url,
            model=model,
            text="hi",
            sampling_params=sampling_params,
            think=False,
            max_images=1,
        )

        self.assertIsNotNone(_last_image(response))

    def test_interleave_quality_image_is_not_blank_or_noise(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        sampling_params = {
            "width": _env_int("SGLANG_OMNI_U1_QUALITY_WIDTH", 1024),
            "height": _env_int("SGLANG_OMNI_U1_QUALITY_HEIGHT", 1024),
            "num_steps": _env_int("SGLANG_OMNI_U1_QUALITY_STEPS", 50),
            "seed": _env_int("SGLANG_OMNI_U1_QUALITY_SEED", 223),
            "cfg_text_scale": _env_float("SGLANG_OMNI_U1_QUALITY_CFG_TEXT_SCALE", 4.0),
            "cfg_img_scale": _env_float("SGLANG_OMNI_U1_QUALITY_CFG_IMG_SCALE", 1.0),
            "cfg_interval": [0.0, 1.0],
            "cfg_renorm_type": "none",
            "t_eps": _env_float("SGLANG_OMNI_U1_QUALITY_T_EPS", 0.02),
        }

        response = _run_turn(
            base_url,
            model=model,
            text="draw me a picture of capybara",
            sampling_params=sampling_params,
            think=False,
            max_images=1,
        )
        image = _last_image(response)
        _save_output_image(response, "SGLANG_OMNI_U1_QUALITY_OUTPUT_IMAGE")
        stats = _image_stats(image)

        self.assertGreaterEqual(
            stats["std"],
            _env_float("SGLANG_OMNI_U1_QUALITY_MIN_IMAGE_STD", 3.0),
            stats,
        )
        self.assertLessEqual(
            stats["edge_mean"],
            _env_float("SGLANG_OMNI_U1_QUALITY_MAX_EDGE_MEAN", 60.0),
            stats,
        )

    def test_t2i_think_medium_generates_clean_reasoning_and_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        sampling_params = {
            "width": _env_int("SGLANG_OMNI_U1_T2I_THINK_WIDTH", 512),
            "height": _env_int("SGLANG_OMNI_U1_T2I_THINK_HEIGHT", 512),
            "num_steps": _env_int("SGLANG_OMNI_U1_T2I_THINK_STEPS", 24),
            "seed": _env_int("SGLANG_OMNI_U1_T2I_THINK_SEED", 223),
            "cfg_text_scale": _env_float(
                "SGLANG_OMNI_U1_T2I_THINK_CFG_TEXT_SCALE", 1.0
            ),
            "cfg_img_scale": _env_float("SGLANG_OMNI_U1_T2I_THINK_CFG_IMG_SCALE", 1.0),
            "cfg_interval": [0.0, 1.0],
            "cfg_renorm_type": "none",
            "t_eps": _env_float("SGLANG_OMNI_U1_T2I_THINK_T_EPS", 0.02),
        }

        response = _run_turn(
            base_url,
            model=model,
            task="t2i",
            text=THREE_TURN_PROMPTS[0],
            sampling_params=sampling_params,
            think=True,
            max_images=1,
        )
        text = "\n".join(
            segment.get("text", "")
            for segment in response.get("segments", [])
            if segment.get("type") == "text"
        )
        image = _last_image(response)
        _save_output_image(response, "SGLANG_OMNI_U1_T2I_THINK_OUTPUT_IMAGE")
        stats = _image_stats(image)

        self.assertNotIn("<think>\n<think>", text)
        self.assertLessEqual(text.count("<think>"), 1, text[:512])
        self.assertLessEqual(text.count("</think>"), 1, text[:512])
        self.assertGreaterEqual(
            stats["std"],
            _env_float("SGLANG_OMNI_U1_T2I_THINK_MIN_IMAGE_STD", 3.0),
            stats,
        )
        self.assertLessEqual(
            stats["edge_mean"],
            _env_float("SGLANG_OMNI_U1_T2I_THINK_MAX_EDGE_MEAN", 70.0),
            stats,
        )

    def test_edit_think_medium_generates_clean_reasoning_and_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        sampling_params = {
            "width": _env_int("SGLANG_OMNI_U1_EDIT_THINK_WIDTH", 512),
            "height": _env_int("SGLANG_OMNI_U1_EDIT_THINK_HEIGHT", 512),
            "num_steps": _env_int("SGLANG_OMNI_U1_EDIT_THINK_STEPS", 24),
            "seed": _env_int("SGLANG_OMNI_U1_EDIT_THINK_SEED", 223),
            "cfg_text_scale": _env_float(
                "SGLANG_OMNI_U1_EDIT_THINK_CFG_TEXT_SCALE", 1.0
            ),
            "cfg_img_scale": _env_float("SGLANG_OMNI_U1_EDIT_THINK_CFG_IMG_SCALE", 1.0),
            "cfg_interval": [0.0, 1.0],
            "cfg_renorm_type": "none",
            "t_eps": _env_float("SGLANG_OMNI_U1_EDIT_THINK_T_EPS", 0.02),
        }

        first = _run_turn(
            base_url,
            model=model,
            task="t2i",
            text=THREE_TURN_PROMPTS[0],
            sampling_params={
                **sampling_params,
                "seed": _env_int("SGLANG_OMNI_U1_EDIT_THINK_FIRST_SEED", 223),
            },
            think=False,
            max_images=1,
        )
        edit = _run_turn(
            base_url,
            model=model,
            task="edit",
            text=THREE_TURN_PROMPTS[1],
            messages=[
                _image_segment_from_payload(first),
                {"type": "text", "text": THREE_TURN_PROMPTS[1]},
            ],
            sampling_params={
                **sampling_params,
                "seed": _env_int("SGLANG_OMNI_U1_EDIT_THINK_EDIT_SEED", 224),
            },
            think=True,
            max_images=1,
        )
        text = "\n".join(
            segment.get("text", "")
            for segment in edit.get("segments", [])
            if segment.get("type") == "text"
        )
        image = _last_image(edit)
        _save_output_image(edit, "SGLANG_OMNI_U1_EDIT_THINK_OUTPUT_IMAGE")
        stats = _image_stats(image)

        self.assertLessEqual(_max_repeated_token_run(text, "1"), 8, text[:512])
        self.assertLessEqual(_max_repeated_char_run(text, "1"), 8, text[:512])
        self.assertGreaterEqual(
            stats["std"],
            _env_float("SGLANG_OMNI_U1_EDIT_THINK_MIN_IMAGE_STD", 3.0),
            stats,
        )
        self.assertLessEqual(
            stats["edge_mean"],
            _env_float("SGLANG_OMNI_U1_EDIT_THINK_MAX_EDGE_MEAN", 70.0),
            stats,
        )

    def test_interleave_long_pre_image_text_generates_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        sampling_params = {
            "width": _env_int("SGLANG_OMNI_U1_LONG_TEXT_WIDTH", 512),
            "height": _env_int("SGLANG_OMNI_U1_LONG_TEXT_HEIGHT", 512),
            "num_steps": _env_int("SGLANG_OMNI_U1_LONG_TEXT_STEPS", 4),
            "seed": _env_int("SGLANG_OMNI_U1_LONG_TEXT_SEED", 223),
            "cfg_text_scale": _env_float(
                "SGLANG_OMNI_U1_LONG_TEXT_CFG_TEXT_SCALE", 4.0
            ),
            "cfg_img_scale": _env_float("SGLANG_OMNI_U1_LONG_TEXT_CFG_IMG_SCALE", 1.0),
            "cfg_interval": [0.0, 1.0],
            "cfg_renorm_type": "none",
            "t_eps": _env_float("SGLANG_OMNI_U1_LONG_TEXT_T_EPS", 0.02),
        }

        response = _run_turn(
            base_url,
            model=model,
            text=(
                "Create one clean studio product image of a matte cobalt-blue cube "
                "centered on a white tabletop, plain light-gray background."
            ),
            sampling_params=sampling_params,
            think=False,
            max_images=1,
        )

        self.assertIsNotNone(_last_image(response))

    def test_interleave_think_multiturn_edit_generates_second_image(self):
        base_url = os.getenv("SGLANG_OMNI_U1_BASE_URL", "http://127.0.0.1:30000")
        model = os.getenv("SGLANG_OMNI_U1_MODEL", "sensenova-u1")
        sampling_params = {
            "width": _env_int("SGLANG_OMNI_U1_THINK_WIDTH", 512),
            "height": _env_int("SGLANG_OMNI_U1_THINK_HEIGHT", 512),
            "num_steps": _env_int("SGLANG_OMNI_U1_THINK_STEPS", 4),
            "seed": _env_int("SGLANG_OMNI_U1_THINK_SEED", 223),
            "cfg_text_scale": _env_float("SGLANG_OMNI_U1_THINK_CFG_TEXT_SCALE", 4.0),
            "cfg_img_scale": _env_float("SGLANG_OMNI_U1_THINK_CFG_IMG_SCALE", 1.0),
            "cfg_interval": [0.0, 1.0],
            "cfg_renorm_type": "none",
            "t_eps": _env_float("SGLANG_OMNI_U1_THINK_T_EPS", 0.02),
        }
        session_id = None
        try:
            first = _run_turn(
                base_url,
                model=model,
                text=THREE_TURN_PROMPTS[0],
                sampling_params=sampling_params,
                keep_session=True,
                think=True,
                max_images=1,
            )
            session_id = first["session"]["id"]
            self.assertIsNotNone(_last_image(first))

            second = _run_turn(
                base_url,
                model=model,
                text=THREE_TURN_PROMPTS[1],
                sampling_params={
                    **sampling_params,
                    "seed": _env_int("SGLANG_OMNI_U1_THINK_EDIT_SEED", 224),
                },
                session_id=session_id,
                think=True,
                max_images=1,
            )
            self.assertIsNotNone(_last_image(second))
        finally:
            if session_id is not None:
                _post_json(
                    base_url,
                    "/v1/omni/generate",
                    {"action": "close_session", "session_id": session_id},
                    raise_on_error=False,
                )


def _run_turn(
    base_url: str,
    *,
    model: str,
    text: str,
    sampling_params: dict,
    task: str = "interleave",
    messages: list[dict] | None = None,
    session_id: str | None = None,
    keep_session: bool = False,
    think: bool = False,
    max_images: int | None = None,
) -> dict:
    payload = {
        "model": model,
        "task": task,
        "think": think,
        "messages": messages or [{"type": "text", "text": text}],
        "sampling_params": sampling_params,
    }
    if max_images is not None:
        payload["max_images"] = max_images
    if session_id is not None:
        payload["session_id"] = session_id
    if keep_session:
        payload["keep_session"] = True
    return _post_json(base_url, "/v1/omni/generate", payload)


def _post_json(
    base_url: str,
    path: str,
    payload: dict,
    *,
    raise_on_error: bool = True,
) -> dict:
    request = Request(
        f"{base_url.rstrip('/')}{path}",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urlopen(
            request,
            timeout=_env_float("SGLANG_OMNI_U1_HTTP_TIMEOUT", 600.0),
        ) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        if not raise_on_error:
            return {}
        body = exc.read().decode("utf-8", errors="replace")
        raise AssertionError(f"omni request failed: {exc.code} {body}") from exc


def _last_image(payload: dict) -> Image.Image:
    for segment in reversed(payload.get("segments", [])):
        if segment.get("type") == "image":
            return _decode_image(segment.get("image"))
    raise AssertionError(f"omni response did not contain an image: {payload}")


def _decode_image(payload) -> Image.Image:
    if isinstance(payload, dict):
        payload = payload.get("b64_json") or payload.get("data")
    if not isinstance(payload, str):
        raise AssertionError(f"unsupported image payload: {type(payload).__name__}")
    if "," in payload and payload.lstrip().startswith("data:"):
        payload = payload.split(",", 1)[1]
    return Image.open(BytesIO(base64.b64decode(payload))).convert("RGB")


def _save_output_image(payload: dict, env_name: str) -> None:
    output_path = os.getenv(env_name)
    if output_path:
        _last_image(payload).save(output_path)


def _assert_reference_match(
    payload: dict,
    *,
    reference_env: str,
    default_reference_path: Path,
    output_env: str,
    metric_prefix: str,
) -> None:
    actual = _last_image(payload)
    reference = Image.open(
        _path_from_env(reference_env, default_reference_path)
    ).convert("RGB")
    metrics = _compare_images(actual, reference)

    output_path = os.getenv(output_env)
    if output_path:
        actual.save(output_path)

    min_psnr = _env_float(f"{metric_prefix}_MIN_PSNR", 22.0)
    max_mae = _env_float(f"{metric_prefix}_MAX_MAE", 80.0)
    min_cosine = _env_float(f"{metric_prefix}_MIN_COSINE", 0.95)
    if metrics["psnr"] < min_psnr:
        raise AssertionError(metrics)
    if metrics["mae"] > max_mae:
        raise AssertionError(metrics)
    if metrics["cosine"] < min_cosine:
        raise AssertionError(metrics)


def _compare_images(actual: Image.Image, reference: Image.Image) -> dict[str, float]:
    if actual.size != reference.size:
        raise AssertionError(f"image size mismatch: {actual.size} != {reference.size}")
    actual_arr = np.asarray(actual, dtype=np.float32) / 255.0
    reference_arr = np.asarray(reference, dtype=np.float32) / 255.0
    diff = actual_arr - reference_arr
    mse = float(np.mean(diff * diff))
    mae = float(np.mean(np.abs(diff)) * 255.0)
    psnr = math.inf if mse == 0.0 else float(20.0 * math.log10(1.0 / math.sqrt(mse)))
    actual_flat = actual_arr.reshape(-1)
    reference_flat = reference_arr.reshape(-1)
    cosine = float(
        np.dot(actual_flat, reference_flat)
        / (np.linalg.norm(actual_flat) * np.linalg.norm(reference_flat))
    )
    return {"psnr": psnr, "mae": mae, "cosine": cosine}


def _image_stats(image: Image.Image) -> dict[str, float]:
    gray = image.convert("L")
    values = np.asarray(gray, dtype=np.float32)
    edges = np.asarray(gray.filter(ImageFilter.FIND_EDGES), dtype=np.float32)
    return {
        "mean": float(np.mean(values)),
        "std": float(np.std(values)),
        "edge_mean": float(np.mean(edges)),
    }


def _env_int(name: str, default: int) -> int:
    return int(os.getenv(name, str(default)))


def _env_float(name: str, default: float) -> float:
    return float(os.getenv(name, str(default)))


def _precision_sampling_params(
    env_prefix: str,
    *,
    default_width: int = 1024,
    default_height: int = 1024,
    default_num_steps: int = 50,
    default_cfg_text_scale: float = 4.0,
    default_cfg_img_scale: float = 1.0,
) -> dict:
    return {
        "width": _env_int(f"{env_prefix}_WIDTH", default_width),
        "height": _env_int(f"{env_prefix}_HEIGHT", default_height),
        "num_steps": _env_int(f"{env_prefix}_STEPS", default_num_steps),
        "seed": _env_int(f"{env_prefix}_SEED", 223),
        "cfg_text_scale": _env_float(
            f"{env_prefix}_CFG_TEXT_SCALE", default_cfg_text_scale
        ),
        "cfg_img_scale": _env_float(
            f"{env_prefix}_CFG_IMG_SCALE", default_cfg_img_scale
        ),
        "cfg_interval": [
            _env_float(f"{env_prefix}_CFG_START", 0.0),
            _env_float(f"{env_prefix}_CFG_END", 1.0),
        ],
        "cfg_renorm_type": os.getenv(f"{env_prefix}_CFG_RENORM_TYPE", "none"),
        "t_eps": _env_float(f"{env_prefix}_T_EPS", 0.02),
    }


def _image_segment_from_path(path: str) -> dict:
    with open(path, "rb") as image_file:
        image_b64 = base64.b64encode(image_file.read()).decode("ascii")
    return {
        "type": "image",
        "image": {"b64_json": image_b64},
    }


def _image_segment_from_payload(payload: dict) -> dict:
    for segment in reversed(payload.get("segments", [])):
        if segment.get("type") == "image":
            return {"type": "image", "image": segment.get("image")}
    raise AssertionError(f"omni response did not contain an image: {payload}")


def _max_repeated_token_run(text: str, token: str) -> int:
    max_run = 0
    current = 0
    for piece in text.split():
        normalized = piece.strip(".,;:!?()[]{}\"'")
        if normalized == token:
            current += 1
            max_run = max(max_run, current)
        else:
            current = 0
    return max_run


def _max_repeated_char_run(text: str, char: str) -> int:
    max_run = 0
    current = 0
    for value in text:
        if value == char:
            current += 1
            max_run = max(max_run, current)
        else:
            current = 0
    return max_run


def _path_from_env(name: str, default: Path) -> str:
    return os.getenv(name) or str(default)


if __name__ == "__main__":
    unittest.main()
