#!/bin/bash
set -e

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >&2
}

# Minimal envs aligned with entrypoint_sglang_native.sh
export MODEL_PATH="${MODEL_PATH:?MODEL_PATH is required}"
export TP_SIZE="${TP_SIZE:-1}"
export DTYPE="${DTYPE:-auto}"
export HOST="${HOST:-0.0.0.0}"
export PORT="${PORT:-8000}"
export QUANTIZATION="${QUANTIZATION:-}"
export KV_CACHE_DTYPE="${KV_CACHE_DTYPE:-auto}"
export MAX_TOTAL_TOKENS="${MAX_TOTAL_TOKENS:-}"
export MEM_FRACTION_STATIC="${MEM_FRACTION_STATIC:-}"
export MAX_RUNNING_REQUESTS="${MAX_RUNNING_REQUESTS:-}"
export CUDA_GRAPH_MAX_BS="${CUDA_GRAPH_MAX_BS:-}"
export CHUNKED_PREFILL_SIZE="${CHUNKED_PREFILL_SIZE:-}"
export SCHEDULE_CONSERVATIVENESS="${SCHEDULE_CONSERVATIVENESS:-1.0}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export ENABLE_METRICS="${ENABLE_METRICS:-true}"
export TRUST_REMOTE_CODE="${TRUST_REMOTE_CODE:-false}"
export CHAT_TEMPLATE="${CHAT_TEMPLATE:-}"
export TOOL_CALL_PARSER="${TOOL_CALL_PARSER:-}"
export API_KEY="${API_KEY:-${HATHORA_APP_SECRET:-}}"
export IS_EMBEDDING="${IS_EMBEDDING:-}"
export SPEC_DECODE="${SPEC_DECODE:-}"
export SPECULATIVE_ALGORITHM="${SPECULATIVE_ALGORITHM:-}"
export SPECULATIVE_DRAFT_MODEL_PATH="${SPECULATIVE_DRAFT_MODEL_PATH:-}"
export SPECULATIVE_NUM_STEPS="${SPECULATIVE_NUM_STEPS:-}"
export DISAGGREGATION_DECODE_TP="${DISAGGREGATION_DECODE_TP:-}"
export DISAGGREGATION_PREFILL_PP="${DISAGGREGATION_PREFILL_PP:-}"
export HF_TOKEN="${HF_TOKEN:-}"

log "Launching Hathora SGLang"
exec python /app/serve_hathora.py
