apiVersion: v1
kind: Service
metadata:
  name: minwm-tianpeng-realtime
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: null
spec:
  loadBalancerClass: eks.amazonaws.com/nlb

