[package]
name = "sglang-storage"
description = "Native storage primitives for SGLang"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.sglang]
python-module = "sglang.srt.rust_extensions._storage"
debug = false

[lib]
name = "sglang_storage_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { workspace = true }
libc = { workspace = true }

[features]
default = ["pyo3/extension-module"]
