apiVersion: v1
kind: Service
metadata:
  name: sgl-router
  namespace: sglang-pd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sgl-router
  ports:
    - name: http
      port: 30000
      targetPort: 30000
      protocol: TCP
