export const config = {
  modelName: "Ling-3.0-flash",

  supportedHardware: ["h20-3e", "h200", "h800", "h100", "b200"],

  hardware: [
    { id: "h20-3e", label: "H20-3e", vram: "141GB", vendor: "nvidia" },
    { id: "h800", label: "H800", vram: "80GB", vendor: "nvidia" },
  ],

  variants: [
    { id: "default", label: "Ling-3.0-flash" },
  ],
  quantizations: [
    { id: "bf16", label: "BF16" },
    { id: "fp8", label: "FP8" },
  ],
  strategies: [
    { id: "low-latency", label: "Low-Latency" },
    { id: "balanced", label: "Balanced" },
  ],
  nodesOptions: [
    { id: "single", label: "Single Node" },
  ],

  modelNames: {
    "default|bf16": "inclusionAI/Ling-3.0-flash",
    "default|fp8": "inclusionAI/Ling-3.0-flash-fp8",
  },

  placeholders: {
    HOST_IP:      { target: "command", label: "Bind host",          default: "0.0.0.0"              },
    PORT:         { target: "command", label: "Bind port",          default: "30000"                },
    DSPARK_DRAFT: { target: "command", label: "DSpark draft model", default: "<dspark-draft-model>" },
    HF_TOKEN:     { target: "command", label: "HF token (Docker)",  default: "<your-hf-token>"      },
    CURL_HOST:    { target: "curl",    label: "Server host",        default: "localhost"            },
    CURL_PORT:    { target: "curl",    label: "Server port",        default: "30000"                },
  },

  curl: `curl http://{{CURL_HOST}}:{{CURL_PORT}}/v1/chat/completions \\
-H 'Content-Type: application/json' \\
-d '{ "model": "{{MODEL_NAME}}", "messages": [{"role":"user","content":"What is the capital of France?"}] }'`,

  dockerImages: {
    "h20-3e": "lmsysorg/sglang:dev",
    "h200": "lmsysorg/sglang:dev",
    "h800": "lmsysorg/sglang:dev",
    "h100": "lmsysorg/sglang:dev",
    "b200": "lmsysorg/sglang:dev",
  },

  benchmarkCommands: {
    speed: `python3 -m sglang.bench_serving \\
  --backend sglang \\
  --host {{CURL_HOST}} --port {{CURL_PORT}} \\
  --model {{MODEL_NAME}} \\
  --dataset-name {{DATASET}} \\
  --random-input-len {{ISL}} --random-output-len {{OSL}} \\
  --num-prompts {{NUM_PROMPTS}} --max-concurrency {{MAX_CONCURRENCY}} \\
  --flush-cache`,
    accuracy: {
      gsm8k_pct: `# To install sgl-eval: pip install git+https://github.com/sgl-project/sgl-eval
sgl-eval run gsm8k \\
  --base-url http://{{CURL_HOST}}:{{CURL_PORT}}/v1 \\
  --num-threads 32`,
    },
  },

  accuracyLabels: [
    ["gsm8k_pct", "GSM8K", "%"],
  ],

  github: {
    cookbookModel: "inclusionAI/Ling-3.0-flash",
  },

  playgroundFeatures: {
    attention: {
      knobs: [
        { id: "tp", label: "TP", values: [null, 4, 8] },
      ],
    },
    parsers: {
      items: [
        { id: "reasoning", label: "Reasoning Parser", flag: "--reasoning-parser ling3" },
        { id: "toolCall", label: "Tool Call Parser", flag: "--tool-call-parser ling3" },
      ],
    },
    speculative: {
      options: [
        { id: "current", label: "Inherited from base" },
        { id: "off", label: "Off (greedy)" },
        { id: "nextn", label: "NEXTN (built-in MTP)", flags: ["--speculative-algorithm NEXTN"] },
        { id: "dspark", label: "DSPARK",
          flags: ["--speculative-algorithm DSPARK", "--speculative-draft-model-path {{DSPARK_DRAFT}}"] },
      ],
    },
  },

  cells: [
    {
      match: { hw: "h20-3e", variant: "default", quant: "bf16", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 4",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "h200", variant: "default", quant: "bf16", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 4",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "h800", variant: "default", quant: "bf16", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 8",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "h100", variant: "default", quant: "bf16", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 8",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "b200", variant: "default", quant: "bf16", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 4",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "h20-3e", variant: "default", quant: "fp8", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 4",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "h200", variant: "default", quant: "fp8", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 4",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "h800", variant: "default", quant: "fp8", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 8",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "h100", variant: "default", quant: "fp8", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 8",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "b200", variant: "default", quant: "fp8", strategy: "balanced", nodes: "single" },
      verified: false,
      env: [],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 4",
        "--enable-cache-report",
        "--log-level info",
        "--enable-metrics",
        "--mem-fraction-static 0.85",
        "--max-running-requests 64",
        "--chunked-prefill-size 8192",
        "--allow-auto-truncate",
        "--enable-trace",
        "--context-length 262144",
        "--max-mamba-cache-size 320",
        "--speculative-algorithm NEXTN",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
    {
      match: { hw: "b200", variant: "default", quant: "bf16", strategy: "low-latency", nodes: "single" },
      verified: false,
      env: ["SGLANG_RAGGED_VERIFY_MODE=static"],
      flags: [
        "--model-path {{MODEL_NAME}}",
        "--tp 4",
        "--speculative-algorithm DSPARK",
        "--speculative-draft-model-path {{DSPARK_DRAFT}}",
        "--disable-radix-cache",
        "--mem-fraction-static 0.8",
        "--flashinfer-allreduce-fusion-backend auto",
        "--scheduler-recv-interval 16",
        "--json-model-override-args '{\"rope_scaling\":{\"rope_type\":\"yarn\",\"factor\":2.0,\"rope_theta\":6000000,\"partial_rotary_factor\":0.5,\"original_max_position_embeddings\":131072}}'",
        "--host {{HOST_IP}}",
        "--port {{PORT}}",
      ],
    },
  ],
};
