# Copyright (c) 2026, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Reproduce the qualified V6 selectors from the unchanged legacy 1024-bin source.

The generated bytes must match the artifacts used in all 80 current-main runs.
These transforms add exact-fallback physical IDs, R1 shared candidates, and
fixed-128-CTA device row/part routing. Both full exact fallback branches remain.
No CuTe import or GPU access is needed to generate/check the sources.
"""
import hashlib
import textwrap

BASE_SHA256 = "faa13c98f6d59eb74961e3649b1175b89c9976c4d22a2239a3d560112600b2c4"
VENDOR_SHA256 = "dceaeec021126b7a72e4a9428d3e4d8e014e1d8d211f063396cf0f011f572195"
SOURCE_SHA256 = {
    "small": "0574e383697ccdec76f6a3c18fc4e6e060a73c8955c1736da4ffeba99898d561",
    "large": "f200bdabf3aea42dfc4d031a7637de3e45b8662c524f65ce42b11792c8c7737c",
}


def replace(text, old, new):
    if text.count(old) != 1:
        raise ValueError(f"fused source anchor count != 1: {old[:100]!r}")
    return text.replace(old, new, 1)


LOCAL_BRANCH = """
if local_fast != cutlass.Int32(0):
    # R==1: retain strict/boundary partitioning without a global hand-off.
    # The gate guarantees both the full list and its boundary subset fit in
    # CMPB. s_ck64 is unused before P5; use it as a temporary second buffer.
    listN = myn
    if split_mode != cutlass.Int32(0):
        # The prologue zeroed s_scal[1:3]; P3 only changes s_scal[0].
        # SPLIT has one attempt, so the published zeros remain available.
        it2 = (myn + cutlass.Int32(BLK - 1)) // cutlass.Int32(BLK)
        it = cutlass.Int32(0)
        while it < it2:
            i = it * cutlass.Int32(BLK) + tidx
            p1 = cutlass.Int32(0)
            p2 = cutlass.Int32(0)
            w64 = cutlass.Uint64(0)
            idv = cutlass.Int32(0)
            if i < myn:
                w64 = cutlass.Uint64(s_cbuf2[i])
                xb = cutlass.Int32(cutlass.Uint32(w64 & cutlass.Uint64(0xFFFFFFFF)))
                idv = cutlass.Int32(cutlass.Uint32(w64 >> cutlass.Uint64(32)))
                if C.f32_of_i32(xb) >= HICs:
                    p1 = cutlass.Int32(1)
                else:
                    p2 = cutlass.Int32(1)
            n1 = C.ballot(p1 != cutlass.Int32(0))
            n2 = C.ballot(p2 != cutlass.Int32(0))
            bhi = cutlass.Int32(0)
            blo = cutlass.Int32(0)
            if lane == cutlass.Int32(0):
                if n1 != cutlass.Int32(0):
                    bhi = C.atomic_add_cta(s_scal.iterator + 1, cutlass.Int32(C.popc(n1)))
                if n2 != cutlass.Int32(0):
                    blo = C.atomic_add_cta(s_scal.iterator + 2, cutlass.Int32(C.popc(n2)))
            bhi = cute.arch.shuffle_sync(bhi, cutlass.Int32(0))
            blo = cute.arch.shuffle_sync(blo, cutlass.Int32(0))
            lm = cutlass.Int32(cute.arch.lanemask_lt())
            if p1 != cutlass.Int32(0):
                p = bhi + cutlass.Int32(C.popc(n1 & lm))
                if p < k:
                    out_row[p] = ptable[tbase + (idv >> cutlass.Int32(6))] * cutlass.Int32(64) + (idv & cutlass.Int32(63))
            if p2 != cutlass.Int32(0):
                p = blo + cutlass.Int32(C.popc(n2 & lm))
                if p < cutlass.Int32(CMPB):
                    s_ck64[p] = w64
            it = it + cutlass.Int32(1)
        # All candidates are read before s_cbuf2 is reused. The two buffers
        # never alias; in-place compaction here would race across warps.
        cute.arch.barrier()
        if tidx == cutlass.Int32(0):
            s_cert[2] = s_scal[1]
        listN = s_scal[2]
        i = tidx
        while i < listN:
            s_cbuf2[i] = s_ck64[i]
            i = i + cutlass.Int32(BLK)
    # With one CTA, its histogram read is already complete. No arrival
    # counter or workspace cursor was touched, including the non-split case.
    if hrestore != cutlass.Int32(0):
        hz = tidx
        while hz < cutlass.Int32(1024):
            histogram[hbase + hz] = cutlass.Int32(0)
            hz = hz + cutlass.Int32(BLK)
    i = tidx
    while i < listN:
        w64 = cutlass.Uint64(s_cbuf2[i])
        gvx = cutlass.Int32(cutlass.Uint32(w64 & cutlass.Uint64(0xFFFFFFFF)))
        bq = C.f2s_rz((C.f32_of_i32(gvx) - TF) * SC)
        if bq > cutlass.Int32(NBS - 1):
            bq = cutlass.Int32(NBS - 1)
        _red_shared_add1(hb_pin + (bq << cutlass.Int32(2)))
        i = i + cutlass.Int32(BLK)
    # Publishes the fine histogram, compacted candidates and strict count.
    # P5 may reuse s_ck64 only after every thread finished the copy above.
    cute.arch.barrier()
    if split_mode != cutlass.Int32(0):
        soff = s_cert[2]
        ksc = k - soff
    C.scan_cross0(
        s_hist, ksc, tidx, s_res,
        cutlass.Int32(0), cutlass.Int32(0), s_hist,
        nb=NBS, zero=False,
    )
    cute.arch.barrier()
    alive = cutlass.Int32(1)
    fromg = cutlass.Int32(0)
    if s_res[C.RES_TOT] >= ksc:
        valid = cutlass.Int32(1)
        complete = cutlass.Int32(1)
        above = s_res[C.RES_ABOVE]
        m = s_res[C.RES_M]
        need = ksc - above
        B = s_res[C.RES_B]
    running = cutlass.Int32(0)
else:
"""


DEVICE_GEOMETRY = """
bx, _, _ = cute.arch.block_idx()  # fixed flat 128-CTA grid
lane = tidx & cutlass.Int32(31)
active = active_batch[0]
valid_active = active
if active < cutlass.Int32(0) or active > cutlass.Int32(logits.shape[0]):
    valid_active = cutlass.Int32(0)
# Same row-part counts as the short-length static policy, with
# capacity-independent device routing. Shifts make division exact.
part_shift = cutlass.Int32(0)
if valid_active > cutlass.Int32(0):
    if valid_active <= cutlass.Int32(2):
        part_shift = cutlass.Int32(6)
    elif valid_active <= cutlass.Int32(8):
        part_shift = cutlass.Int32(4)
    elif valid_active <= cutlass.Int32(16):
        part_shift = cutlass.Int32(3)
    elif valid_active <= cutlass.Int32(32):
        part_shift = cutlass.Int32(2)
    elif valid_active <= cutlass.Int32(64):
        part_shift = cutlass.Int32(1)
R = cutlass.Int32(1) << part_shift
row = bx >> part_shift
part = bx & (R - cutlass.Int32(1))
inactive = cutlass.Int32(0)
if row >= valid_active:
    inactive = cutlass.Int32(1)

# A CTA may both clear an inactive storage row and select an active
# request. The two row sets are disjoint. This does not rely on spare
# selection CTAs: active*R can consume the whole fixed grid.
if bx >= valid_active and bx < cutlass.Int32(logits.shape[0]):
    clear_row = bx
    if tidx < cutlass.Int32(6):
        diagnostics[clear_row, tidx] = cutlass.Int32(-2)
    i = tidx
    while i < k:
        out[clear_row, i] = cutlass.Int32(-1)
        i = i + cutlass.Int32(BLK)
    i = tidx
    while i < cutlass.Int32(1024):
        histogram[clear_row * cutlass.Int32(1024) + i] = cutlass.Int32(0)
        i = i + cutlass.Int32(BLK)
    if tidx == cutlass.Int32(0):
        ws[clear_row * cutlass.Int32(2)] = cutlass.Int32(0)
        ws[clear_row * cutlass.Int32(2) + cutlass.Int32(1)] = cutlass.Int32(0)
        ws[cutlass.Int32(320) + clear_row] = cutlass.Int32(0)
        tail_word = cutlass.Int32(WS_TAIL_OFF__batched // 4) + clear_row * cutlass.Int32(2)
        ws[tail_word] = cutlass.Int32(0)
        ws[tail_word + cutlass.Int32(1)] = cutlass.Int32(0)

"""


def source(base, vendor, route):
    if route not in SOURCE_SHA256:
        raise ValueError("route must be small or large")
    for text, expected in ((base, BASE_SHA256), (vendor, VENDOR_SHA256)):
        if hashlib.sha256(text.encode()).hexdigest() != expected:
            raise ValueError("unqualified legacy selector/vendor source")
    # Override inherited logical-ID emission in all radix/tie fallbacks.
    start = vendor.index("    @cute.jit\n    def _ballot_pair_emit(")
    end = vendor.index("    # ------------------------------------------------------------------", start)
    helper = vendor[start:end].replace("_ballot_pair_emit", "_physical_ballot_pair_emit")
    helper = helper.replace("s_scal, lane):", "s_scal, lane, ptable, tbase):")
    helper = helper.replace("= idv\n", "= ptable[tbase + (idv >> cutlass.Int32(6))] * cutlass.Int32(64) + (idv & cutlass.Int32(63))\n")
    text = replace(base, "    @cute.kernel\n    def kern(", helper + "    @cute.kernel\n    def kern(")
    text = text.replace("self._ballot_pair_emit(", "self._physical_ballot_pair_emit(")
    text = text.replace("out_row, s_scal, lane\n", "out_row, s_scal, lane, ptable, tbase\n")
    text = text.replace("                                    lane,\n", "                                    lane, ptable, tbase,\n")

    # Preserve the original publication/fallback block under an R1 local branch.
    anchor = "                if cutlass.const_expr(self.split):\n                    pubn = myn\n"
    start = text.index(anchor) + len("                if cutlass.const_expr(self.split):\n")
    end = text.index("                else:\n                    # ---- non-split verify + rung ladder ----\n", start)
    old = text[start:end]
    gate = """                    local_fast = cutlass.Int32(0)
                    if s_cert[3] == cutlass.Int32(1):
                        if cert_fast != cutlass.Int32(0):
                            if expected_pass <= cutlass.Int32(CMPB) and myn <= cutlass.Int32(CMPB):
                                local_fast = cutlass.Int32(1)
"""
    text = text[:start] + gate + textwrap.indent(LOCAL_BRANCH.lstrip(), " " * 20) + textwrap.indent(old, " " * 4) + text[end:]

    text = text.replace("        npages: cutlass.Int32,\n", "        npages: cutlass.Int32,\n        active_batch: cute.Tensor,\n")
    if text.count("        active_batch: cute.Tensor,\n") != 2:
        raise ValueError("active-count signature drift")
    text = replace(text, "            npages,\n", "            npages,\n            active_batch,\n")
    start = text.index("        bx, by, _ = cute.arch.block_idx()  # 2-D grid (part, row)\n")
    end = text.index("        # ================= per-row varlen prologue", start)
    text = text[:start] + textwrap.indent(DEVICE_GEOMETRY.lstrip(), " " * 8) + text[end:]
    text = replace(text, "            kvl = kv_lens[req]\n", """            kvl = cutlass.Int32(0)
            if inactive == cutlass.Int32(0):
                kvl = kv_lens[req]
""")
    text = replace(text, "        if part < R:\n", "        if part < R and inactive == cutlass.Int32(0):\n")
    start = text.index("            if cutlass.const_expr(self.r_const == 37):\n")
    end = text.index("            n_row = nv\n", start)
    text = text[:start] + text[end:]
    start = text.index("                    Q = (n4v + cutlass.Int32(self.r_const - 1))")
    end = text.index("                else:\n", start)
    text = text[:start] + "                    Q = (n4v + R - cutlass.Int32(1)) >> part_shift\n" + text[end:]
    text = replace(text, "                        if cutlass.const_expr(self.r_const > 1):\n",
                   "                        if s_cert[3] > cutlass.Int32(1):\n")
    text = replace(text, "                s_cert[2] = cutlass.Int32(0)\n",
                   "                s_cert[2] = cutlass.Int32(0)\n"
                   "                s_cert[3] = R  # immutable runtime part count\n")
    text = replace(text, "                        if cutlass.Int32(pk >> cutlass.Int64(32)) == R - cutlass.Int32(1):\n",
                   "                        if cutlass.Int32(pk >> cutlass.Int64(32)) == s_cert[3] - cutlass.Int32(1):\n")
    text = replace(text, """            if tidx == cutlass.Int32(0):
                drow = row * cutlass.Int32(self.r_const) + part
                diagnostics[drow, 0] = cert_fast
""", """            # One diagnostic record per storage row. All row parts derive
            # identical certificate/threshold fields; part zero owns publication.
            if tidx == cutlass.Int32(0) and part == cutlass.Int32(0):
                drow = row
                diagnostics[drow, 0] = cert_fast
""")
    start = text.index("        else:\n            if tidx < cutlass.Int32(6):\n")
    end = text.index("    # ------------------------------------------------------------------\n    # host launcher", start)
    text = text[:start] + text[end:]
    text = replace(text, ").launch(grid=(R, b, 1),", ").launch(grid=(128, 1, 1),")
    text = text.replace("# host launcher (grid dim3(R, b); MINB wall via min_blocks_per_mp)",
                        "# host launcher (fixed 128 CTAs; active/R ownership is device-only)")
    if "self.r_const" in text or "_certificate_failure_trap" in text:
        raise ValueError("static row-part dependency or certificate-only source")

    if route == "small":
        start = text.index("            h0 = cutlass.Int32(0)\n")
        end = text.index("            hincl =", start)
        text = text[:start] + """            hh = cute.make_rmem_tensor((2,), cutlass.Int32)
            hs = cutlass.Int32(0)
            for hi in cutlass.range_constexpr(2):
                hv = cutlass.Int32(0)
                if short == cutlass.Int32(0):
                    hv = histogram[hbase + tidx * cutlass.Int32(2) + cutlass.Int32(hi)]
                hh[hi] = hv
                hs = hs + hv
""" + text[end:]
        text = replace(text, "            warp_total = s_cbuf[lane]\n",
                       "            warp_total = cutlass.Int32(0)\n"
                       "            if lane < cutlass.Int32(NW):\n"
                       "                warp_total = s_cbuf[lane]\n")
        start = text.index("            run0 = hbefore + hincl - hs\n")
        end = text.index("            cute.arch.barrier()  # crossing", start)
        text = text[:start] + """            running = hbefore + hincl - hs
            if short == cutlass.Int32(0):
                for hi in cutlass.range_constexpr(2):
                    after = running + hh[hi]
                    if running <= k and k < after:
                        s_cbuf[NW + 0] = tidx * cutlass.Int32(2) + cutlass.Int32(hi)
                        s_cbuf[NW + 1] = running
                        s_cbuf[NW + 2] = hh[hi]
                    running = after
                if tidx == cutlass.Int32(BLK - 1):
                    s_cbuf[NW + 3] = running
""" + text[end:]

    # Device guards cover the complete bodies, including inactive-row cleanup.
    start = text.index("        BLK = self.blk\n")
    end = text.index("    # ------------------------------------------------------------------\n    # host launcher", start)
    condition = "!=" if route == "small" else "=="
    guard = """        route_active = active_batch[0]
        route_small = cutlass.Int32(0)
        if route_active > cutlass.Int32(0) and route_active <= cutlass.Int32(8):
            if route_active <= cutlass.Int32(logits.shape[0]):
                route_small = cutlass.Int32(1)
"""
    text = text[:start] + guard + f"        if route_small {condition} cutlass.Int32(0):\n" + textwrap.indent(text[start:end], " " * 4) + text[end:]
    compile(text, f"fused_{route}.py", "exec")
    digest = hashlib.sha256(text.encode()).hexdigest()
    if digest != SOURCE_SHA256[route]:
        raise ValueError(f"qualified {route} source mismatch: {digest}")
    return text
