{{- if include "sglang.createExternalSecret" . }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sglang.fullname" . }}-hf-token
  labels:
    {{- include "sglang.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.hfSecret.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.hfSecret.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "sglang.hfSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.hfSecret.existingSecretKey }}
      remoteRef:
        key: {{ .Values.hfSecret.externalSecret.remoteRef.key }}
{{- end }}
