{{- if include "sglang.createHfSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sglang.hfSecretName" . }}
  labels:
    {{- include "sglang.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.hfSecret.existingSecretKey }}: {{ .Values.hfSecret.token | quote }}
{{- end }}
